/**
 * Caso 006 — "TechBrasil: Sua Primeira Semana como Analista de Dados"
 * 6 fases: OLTP (1-2), Limpeza (3-4), ETL (5-6), Star Schema (7-9), OLAP (10-12), Auditoria (13-14)
 */

export const CASE_INTRO = {
  title: 'Sua Primeira Semana como Analista de Dados',
  subtitle: 'Caso #006 — OLTP, ETL e Data Warehouse',
  story: `Parabéns pela promoção! Você agora é Analista de Dados Jr da TechBrasil. Sua primeira semana: construir o Data Warehouse da empresa. O modelo OLTP que você normalizou no Caso 005 está no ar. Agora é hora de copiar os dados para um DW otimizado para análise, criar o star schema e entregar relatórios para a diretoria. O CFO está esperando.`,
  mission: 'Construa o DW completo: OLTP → Limpeza → ETL → Star Schema → OLAP → Auditoria.',
};

export const CASE_CONCLUSION = {
  title: 'DW Operacional!',
  story: `Incrível! Você construiu o Data Warehouse completo da TechBrasil: explorou o OLTP, limpou dados sujos, montou o ETL, criou o star schema, entregou views de relatório para o CFO e otimizou com índices. O certificado de "Analista de BI" está pronto para download. Bem-vindo à próxima fase da sua carreira!`,
  cargo: 'Analista de BI',
  nextSteps: 'Certificado de Analista de BI disponível para download.',
};

export const DATABASE_ANALYSIS = {
  title: 'O Pipeline de Dados',
  summary: 'O DW da TechBrasil segue o pipeline: OLTP (modelo normalizado) → Staging (dados sujos) → ETL (limpeza + carga) → Star Schema (dimensões + fatos) → OLAP (views de relatório) → Auditoria (índices + triggers). Cada fase tem seu propósito.',
  entities: [
    { name: 'OLTP (clientes, produtos, vendas, itens_venda)', role: 'Sistema transacional normalizado (3FN). Fonte dos dados.', key: 'PKs + FKs', relations: ['Fonte do ETL'] },
    { name: 'Staging (stg_clientes, stg_vendas)', role: 'Área de preparação com dados sujos (espaços, vírgulas, NULLs).', key: 'PK id', relations: ['Entrada do ETL'] },
    { name: 'Dimensões (dim_*)', role: 'Tabelas de contexto: quem, o quê, onde, quando.', key: 'PK id', relations: ['FKs da fct_vendas'] },
    { name: 'Fato (fct_vendas)', role: 'Tabela central com métricas: quantidade, valor.', key: 'PK id', relations: ['FKs → todas as dimensões'] },
    { name: 'Views (vw_*)', role: 'Relatórios prontos para o BI/dashboard.', key: '—', relations: ['SELECT sobre fct + dims'] },
    { name: 'log_auditoria', role: 'Trilha de auditoria via triggers.', key: 'PK id', relations: ['Preenchida automaticamente por triggers'] },
  ],
  decisions: [
    { title: 'Separar OLTP de OLAP', explanation: 'O OLTP é otimizado para escrita (transações). O DW é otimizado para leitura (análise). Separá-los evita conflito de recursos.' },
    { title: 'Limpar antes de carregar', explanation: 'Dados sujos no staging contaminam o DW. Limpeza (TRIM, CAST, REPLACE) é obrigatória antes do ETL.' },
    { title: 'Star schema para análise', explanation: 'Fatos no centro, dimensões ao redor. Minimiza JOINs e acelera consultas analíticas.' },
    { title: 'Views reutilizáveis', explanation: 'Views encapsulam queries complexas em objetos reutilizáveis para dashboards e relatórios.' },
  ],
  checkpoints: [
    { question: 'Por que não rodar queries analíticas direto no OLTP?', answer: 'O OLTP é otimizado para transações rápidas. Queries pesadas de análise competem com as operações do dia a dia e deixam o sistema lento.' },
    { question: 'Qual a diferença entre uma dimensão e uma tabela de fato?', answer: 'Dimensão = contexto (quem, o quê, onde, quando). Fato = métrica (quanto, quantos). A fato tem FKs para as dimensões.' },
    { question: 'Para que serve um índice?', answer: 'Índices aceleram consultas de leitura permitindo ao banco encontrar registros sem varrer a tabela inteira. Trade-off: desaceleram escrita.' },
  ],
};

export const GAMEPLAY = {
  timeline: {
    bonusPoints: 200,
    events: [
      { id: 'fase-01', unlockedByMission: 1, sortKey: '2024-03-01T09:00:00', type: 'fase', label: 'Fase 1: OLTP explorado' },
      { id: 'fase-02', unlockedByMission: 3, sortKey: '2024-03-01T11:00:00', type: 'fase', label: 'Fase 2: Dados limpos no staging' },
      { id: 'fase-03', unlockedByMission: 5, sortKey: '2024-03-01T14:00:00', type: 'fase', label: 'Fase 3: ETL concluído' },
      { id: 'fase-04', unlockedByMission: 7, sortKey: '2024-03-02T09:00:00', type: 'fase', label: 'Fase 4: Star schema montado' },
      { id: 'fase-05', unlockedByMission: 10, sortKey: '2024-03-02T14:00:00', type: 'fase', label: 'Fase 5: Views de relatório entregues' },
      { id: 'fase-06', unlockedByMission: 13, sortKey: '2024-03-03T09:00:00', type: 'fase', label: 'Fase 6: DW otimizado e auditado' },
    ],
  },
  finalChallenge: {
    type: 'confrontation',
    suspectName: 'Diretoria TechBrasil',
    requiredMission: 14,
    steps: [
      { statement: 'Por que não usamos o OLTP diretamente para relatórios?', evidenceId: 'fase-01', successMessage: 'O OLTP é otimizado para transações. Queries analíticas pesadas competem com as operações do dia a dia.' },
      { statement: 'Como você garantiu a qualidade dos dados antes de carregar?', evidenceId: 'fase-02', successMessage: 'Limpeza no staging: TRIM, CAST, REPLACE eliminaram espaços, vírgulas e NULLs.' },
      { statement: 'Qual a estrutura do star schema que você montou?', evidenceId: 'fase-04', successMessage: 'fct_vendas no centro com FKs para dim_tempo, dim_clientes, dim_produtos, dim_vendedores e dim_regioes.' },
      { statement: 'Como otimizou a performance do DW?', evidenceId: 'fase-06', successMessage: 'Índices nas FKs da fct_vendas reduzem o custo do plano de execução de SCAN para SEARCH USING INDEX.' },
    ],
  },
};

export const LEVELS = [
  // ═══════════════════════════════════════════
  // FASE 1: OLTP (missões 1-2)
  // ═══════════════════════════════════════════
  {
    id: 1,
    title: 'Fase 1 — Explorar o OLTP: Vendas por Mês',
    concept: 'GROUP BY + agregação',
    briefing: `Primeiro dia: conheça o modelo OLTP que você construiu no Caso 005. A diretoria quer saber o faturamento mensal. Agrupe as vendas por mês e some os valores.`,
    objective: 'Retorne o mês (data_venda) e o faturamento total (soma de valor_total) por mês, ordenado por mês.',
    tables: ['vendas'],
    expectedColumns: ['mes', 'faturamento'],
    referenceQuery: "SELECT strftime('%Y-%m', data_venda) AS mes, SUM(valor_total) AS faturamento FROM vendas GROUP BY strftime('%Y-%m', data_venda) ORDER BY mes;",
    requiredConcepts: ['group by', 'sum'],
    hints: ['Use strftime("%Y-%m", data_venda) para extrair o mês.', 'Use SUM(valor_total) para agregar.', 'GROUP BY o mês extraído.'],
    courseRefs: ['aggregation'],
    evidence: 'Evidência 1: Faturamento mensal calculado a partir do modelo OLTP normalizado.',
    explanation: 'GROUP BY agrupa linhas por valor e SUM agrega os valores dentro de cada grupo. strftime extrai o ano-mês da data.',
  },
  {
    id: 2,
    title: 'Fase 1 — Explorar o OLTP: Top Produtos',
    concept: 'JOIN + ORDER BY + LIMIT',
    briefing: `Agora cruze vendas com produtos para descobrir os mais vendidos. O JOIN liga itens_venda com produtos pelo produto_id.`,
    objective: 'Retorne o nome do produto, a quantidade total vendida e a receita total, ordenados por quantidade (desc), top 5.',
    tables: ['itens_venda', 'produtos'],
    expectedColumns: ['produto', 'total_vendido', 'receita'],
    referenceQuery: "SELECT p.nome AS produto, SUM(iv.quantidade) AS total_vendido, SUM(iv.quantidade * iv.preco_unitario) AS receita FROM itens_venda iv JOIN produtos p ON iv.produto_id = p.id GROUP BY p.id, p.nome ORDER BY total_vendido DESC LIMIT 5;",
    requiredConcepts: ['join', 'order by', 'limit'],
    hints: ['Use JOIN para ligar itens_venda com produtos.', 'GROUP BY produto para agregar.', 'ORDER BY total_vendido DESC LIMIT 5 para o top.'],
    courseRefs: ['joins-inner'],
    evidence: 'Evidência 2: Top produtos identificados por volume de vendas e receita.',
    explanation: 'JOIN recompõe o contexto entre tabelas normalizadas. GROUP BY + SUM agregam as métricas por produto.',
  },
  // ═══════════════════════════════════════════
  // FASE 2: Limpeza de Dados (missões 3-4)
  // ═══════════════════════════════════════════
  {
    id: 3,
    title: 'Fase 2 — Limpeza: Corrigir Nomes e Espaços',
    concept: 'TRIM + UPPER/LOWER',
    briefing: `O staging está sujo: nomes com espaços extras (" José "), caixa inconsistente ("ana pereira", "CARLOS"). Use TRIM e funções de caixa para padronizar.`,
    objective: 'Liste os nomes dos clientes do staging limpos: sem espaços extras e padronizados para minúsculas.',
    tables: ['stg_clientes'],
    expectedColumns: ['nome_limpo'],
    referenceQuery: "SELECT TRIM(LOWER(nome)) AS nome_limpo FROM stg_clientes ORDER BY id;",
    requiredConcepts: ['trim'],
    hints: ['TRIM remove espaços do início e fim.', 'LOWER padroniza para minúsculas.', 'Combine TRIM(LOWER(nome)) para limpar e padronizar.'],
    courseRefs: ['string-functions'],
    evidence: 'Evidência 3: Nomes limpos e padronizados para o DW.',
    explanation: 'TRIM remove espaços, LOWER/UPPER padronizam caixa. Funções de string são essenciais para data quality.',
  },
  {
    id: 4,
    title: 'Fase 2 — Limpeza: Corrigir Preços com Vírgula',
    concept: 'REPLACE + CAST',
    briefing: `Os preços no staging vêm como texto com vírgula decimal ("3.500,00"). O DW precisa de números REAL. Use REPLACE para remover ponto de milhar, trocar vírgula por ponto, e CAST para converter.`,
    objective: 'Converta os preços do staging para REAL: remova pontos de milhar, troque vírgula por ponto decimal, e caste para REAL.',
    tables: ['stg_vendas'],
    expectedColumns: ['preco_limpo'],
    referenceQuery: "SELECT CAST(REPLACE(REPLACE(TRIM(preco_venda), '.', ''), ',', '.') AS REAL) AS preco_limpo FROM stg_vendas ORDER BY id;",
    requiredConcepts: ['replace', 'cast'],
    hints: ['REPLACE(texto, ".", "") remove milhar.', 'REPLACE(resultado, ",", ".") troca vírgula por ponto.', 'CAST(... AS REAL) converte para número.'],
    courseRefs: ['string-functions'],
    evidence: 'Evidência 4: Preços convertidos para REAL prontos para cálculos no DW.',
    explanation: 'REPLACE encadeado remove formatação brasileira. CAST transforma texto em número. Sem isso, SUM e AVG falham.',
  },
  // ═══════════════════════════════════════════
  // FASE 3: ETL (missões 5-6)
  // ═══════════════════════════════════════════
  {
    id: 5,
    title: 'Fase 3 — ETL: Carga de Dimensão (clientes)',
    concept: 'INSERT INTO ... SELECT',
    briefing: `Carga total: popule a dim_clientes diretamente do staging limpo. Use INSERT INTO ... SELECT com TRIM para limpar os nomes no caminho.`,
    objective: 'Insira na dim_clientes os dados limpos do staging: nome (TRIM), endereco e cidade.',
    tables: ['stg_clientes', 'dim_clientes'],
    expectedColumns: ['id', 'nome', 'endereco', 'cidade'],
    referenceQuery: "INSERT INTO dim_clientes (nome, endereco, cidade) SELECT TRIM(nome), endereco, cidade FROM stg_clientes;",
    expectedRows: 5,
    executionMode: 'ddl',
    requiredConcepts: ['insert'],
    hints: ['Use INSERT INTO dim_clientes (nome, endereco, cidade) SELECT ... FROM stg_clientes.', 'TRIM(nome) limpa espaços extras.', 'SUBSTR + INSTR extraem a cidade do endereço.'],
    courseRefs: ['dml-insert'],
    evidence: 'Evidência 5: dim_clientes populada com registros limpos. Nomes padronizados, cidades extraídas do endereço.',
    explanation: 'INSERT INTO ... SELECT combina criação e carga em uma operação. As transformações (TRIM, SUBSTR) acontecem no caminho.',
  },
  {
    id: 6,
    title: 'Fase 3 — ETL: Carga Incremental (vendas)',
    concept: 'INSERT...SELECT + WHERE NOT EXISTS',
    briefing: `Carga incremental: adicione vendas do staging que ainda não estão na fct_vendas. Use INSERT...SELECT com WHERE NOT EXISTS para evitar duplicatas.`,
    objective: 'Insira na fct_vendas as vendas do staging que ainda não existem (verifique por id). Inclua: tempo_id=1, cliente_id=1, produto_id=1, vendedor_id=1, regiao_id=1, quantidade e valor_total calculados.',
    tables: ['stg_vendas', 'fct_vendas'],
    expectedColumns: ['id', 'tempo_id', 'cliente_id', 'quantidade', 'valor_total'],
    referenceQuery: "INSERT INTO fct_vendas (tempo_id, cliente_id, produto_id, vendedor_id, regiao_id, quantidade, valor_unitario, valor_total) SELECT 1, 1, 1, 1, 1, CAST(quantidade AS INTEGER), CAST(REPLACE(REPLACE(TRIM(preco_venda), '.', ''), ',', '.') AS REAL), CAST(quantidade AS INTEGER) * CAST(REPLACE(REPLACE(TRIM(preco_venda), '.', ''), ',', '.') AS REAL) FROM stg_vendas WHERE id NOT IN (SELECT tempo_id FROM fct_vendas);",
    expectedRows: 5,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'where'],
    hints: ['Use INSERT INTO ... SELECT FROM.', 'Converta quantidade e preço com CAST.', 'Multiplique quantidade × preco para o valor_total.'],
    courseRefs: ['dml-insert'],
    evidence: 'Evidência 6: ETL concluído — vendas do staging carregadas na fct_vendas. O pipeline OLTP → DW está operacional.',
    explanation: 'INSERT...SELECT com WHERE NOT EXISTS é o padrão de carga incremental: só insere o que ainda não existe no destino.',
  },
  // ═══════════════════════════════════════════
  // FASE 4: Star Schema (missões 7-9)
  // ═══════════════════════════════════════════
  {
    id: 7,
    title: 'Fase 4 — Star Schema: Popular Dimensões',
    concept: 'INSERT INTO (dimensões)',
    briefing: `Popule as dimensões do star schema: dim_tempo (datas), dim_produtos (catálogo), dim_regioes (geografia). Cada dimensão descreve um contexto da análise. As tabelas já existem — basta inserir os dados.`,
    objective: 'Insira na dim_tempo as datas únicas das vendas com ano, mês e dia extraídos.',
    tables: ['vendas', 'dim_tempo'],
    expectedColumns: ['id', 'data_completa', 'ano', 'mes', 'dia'],
    referenceQuery: 'INSERT INTO dim_tempo (data_completa, ano, mes, dia) SELECT DISTINCT data_venda, CAST(strftime("%Y", data_venda) AS INTEGER), CAST(strftime("%m", data_venda) AS INTEGER), CAST(strftime("%d", data_venda) AS INTEGER) FROM vendas;',
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'distinct'],
    hints: ['Use INSERT INTO dim_tempo (data_completa, ano, mes, dia) SELECT DISTINCT ...', 'strftime extrai ano, mês e dia.', 'CAST para INTEGER.'],
    courseRefs: ['dml-insert'],
    evidence: 'Evidência 7: dim_tempo populada com datas únicas. A dimensão tempo permite análise temporal.',
    explanation: 'Dimensões descrevem o contexto (quando, onde, quem). A dim_tempo é essencial para análise de tendências e comparativos.',
  },
  {
    id: 8,
    title: 'Fase 4 — Star Schema: Popular a Tabela de Fatos',
    concept: 'INSERT INTO (fato)',
    briefing: `A fct_vendas é o centro do star schema. Contém as métricas (quantidade, valor) e FKs para todas as dimensões. Cada linha = um item de venda. Popule-a com dados do OLTP.`,
    objective: 'Insira na fct_vendas os dados de cada item de venda: tempo_id, cliente_id, produto_id, vendedor_id, regiao_id, quantidade, valor_unitario e valor_total.',
    tables: ['vendas', 'itens_venda', 'produtos', 'fct_vendas'],
    expectedColumns: ['id', 'tempo_id', 'cliente_id', 'produto_id', 'vendedor_id', 'regiao_id', 'quantidade', 'valor_unitario', 'valor_total'],
    referenceQuery: "INSERT INTO fct_vendas (tempo_id, cliente_id, produto_id, vendedor_id, regiao_id, quantidade, valor_unitario, valor_total) SELECT t.id, v.cliente_id, iv.produto_id, v.vendedor_id, v.regiao_id, iv.quantidade, iv.preco_unitario, iv.quantidade * iv.preco_unitario FROM itens_venda iv JOIN vendas v ON iv.venda_id = v.id JOIN dim_tempo t ON t.data_completa = v.data_venda;",
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'join'],
    hints: ['A fato tem FKs para todas as dimensões.', 'JOIN itens_venda com vendas para obter o contexto.', 'valor_total = quantidade × preco_unitario.'],
    courseRefs: ['dml-insert'],
    evidence: 'Evidência 8: fct_vendas populada com 20 linhas (1 por item de venda). Granularidade: item de venda.',
    explanation: 'A tabela de fatos contém métricas e FKs para dimensões. Granularidade = nível de detalhe (aqui: item de venda).',
  },
  {
    id: 9,
    title: 'Fase 4 — Star Schema: SCD Type 1 (Atualizar Vendedor)',
    concept: 'UPDATE (SCD Type 1)',
    briefing: `O vendedor "R. Souza" foi cadastrado como "Rodrigo Souza" no RH. Atualize a dimensão sem perder histórico de vendas passadas. Isso é SCD Type 1: sobrescreve o valor atual.`,
    objective: 'Atualize o nome do vendedor id=2 na dim_vendedores para "Rodrigo Souza" (SCD Type 1).',
    tables: ['dim_vendedores'],
    expectedColumns: ['id', 'nome'],
    referenceQuery: "UPDATE dim_vendedores SET nome = 'Rodrigo Souza' WHERE id = 2;",
    expectedRows: 1,
    executionMode: 'ddl',
    requiredConcepts: ['update'],
    hints: ['Use UPDATE ... SET ... WHERE.', 'SCD Type 1 sobrescreve o valor atual.', 'O histórico das vendas passadas permanece na fct_vendas.'],
    courseRefs: ['dml-update'],
    evidence: 'Evidência 9: Vendedor atualizado na dimensão. As vendas históricas na fct_vendas não são afetadas (SCD Type 1).',
    explanation: 'SCD Type 1 (Slowly Changing Dimension): atualiza o valor atual sem preservar o anterior. Útil quando o histórico não importa.',
  },
  // ═══════════════════════════════════════════
  // FASE 5: OLAP (missões 10-12)
  // ═══════════════════════════════════════════
  {
    id: 10,
    title: 'Fase 5 — OLAP: Faturamento por Região',
    concept: 'GROUP BY + JOIN múltiplo',
    briefing: `O CFO quer o faturamento por região. Cruze fct_vendas com dim_regioes pelo regiao_id e agregue.`,
    objective: 'Retorne o nome da região e o faturamento total (soma de valor_total), agrupado por região, ordenado por faturamento (desc).',
    tables: ['fct_vendas', 'dim_regioes'],
    expectedColumns: ['regiao', 'faturamento'],
    referenceQuery: "SELECT r.nome AS regiao, SUM(f.valor_total) AS faturamento FROM fct_vendas f JOIN dim_regioes r ON f.regiao_id = r.id GROUP BY r.id, r.nome ORDER BY faturamento DESC;",
    requiredConcepts: ['join', 'group by', 'sum'],
    hints: ['JOIN fct_vendas com dim_regioes pelo regiao_id.', 'GROUP BY região para agregar.', 'SUM(valor_total) para o faturamento.'],
    courseRefs: ['aggregation'],
    evidence: 'Evidência 10: Faturamento por região calculado via star schema com apenas 1 JOIN.',
    explanation: 'O star schema minimiza JOINs: fato + 1 dimensão = 1 JOIN. No OLTP normalizado, seriam 5+ JOINs para o mesmo resultado.',
  },
  {
    id: 11,
    title: 'Fase 5 — OLAP: Comparativo Mensal com LAG',
    concept: 'Window Function (LAG)',
    briefing: `O CFO quer comparar o faturamento de cada mês com o anterior. Use LAG() para acessar o valor da linha anterior sem self-join.`,
    objective: 'Retorne o mês, faturamento do mês e faturamento do mês anterior (usando LAG), ordenado por mês.',
    tables: ['fct_vendas', 'dim_tempo'],
    expectedColumns: ['mes', 'faturamento_mes', 'faturamento_anterior'],
    referenceQuery: "SELECT t.mes, SUM(f.valor_total) AS faturamento_mes, LAG(SUM(f.valor_total)) OVER (ORDER BY t.mes) AS faturamento_anterior FROM fct_vendas f JOIN dim_tempo t ON f.tempo_id = t.id GROUP BY t.id, t.mes ORDER BY t.mes;",
    requiredConcepts: ['lag'],
    hints: ['LAG(coluna) OVER (ORDER BY ...) acessa a linha anterior.', 'Combine com GROUP BY para agregar por mês primeiro.', 'O ORDER BY dentro do OVER define a ordem da janela.'],
    courseRefs: ['window-functions'],
    evidence: 'Evidência 11: Comparativo mensal com LAG — o faturamento do mês anterior aparece ao lado.',
    explanation: 'LAG é uma window function que acessa o valor de N linhas antes na janela definida por OVER (ORDER BY ...). Evita self-join.',
  },
  {
    id: 12,
    title: 'Fase 5 — OLAP: Criar View para o Dashboard do CFO',
    concept: 'CREATE VIEW',
    briefing: `Entregue uma view reutilizável para o dashboard do CFO: faturamento por região e mês. A view encapsula a query complexa em um objeto simples de consultar.`,
    objective: 'Crie a view vw_faturamento_regional com região, mês, faturamento e total de itens, agrupado por região e mês.',
    tables: ['fct_vendas', 'dim_regioes', 'dim_tempo'],
    expectedColumns: ['regiao', 'mes', 'faturamento', 'total_itens'],
    referenceQuery: "CREATE VIEW vw_faturamento_regional AS SELECT r.nome AS regiao, t.mes, SUM(f.valor_total) AS faturamento, COUNT(*) AS total_itens FROM fct_vendas f JOIN dim_regioes r ON f.regiao_id = r.id JOIN dim_tempo t ON f.tempo_id = t.id GROUP BY r.nome, t.mes;",
    executionMode: 'create_view',
    viewName: 'vw_faturamento_regional',
    verificationQuery: 'SELECT regiao, mes, faturamento, total_itens FROM vw_faturamento_regional ORDER BY regiao, mes;',
    expectedResultQuery: "SELECT r.nome AS regiao, t.mes, SUM(f.valor_total) AS faturamento, COUNT(*) AS total_itens FROM fct_vendas f JOIN dim_regioes r ON f.regiao_id = r.id JOIN dim_tempo t ON f.tempo_id = t.id GROUP BY r.nome, t.mes ORDER BY regiao, mes;",
    requiredConcepts: ['create view', 'join', 'group by'],
    hints: ['Use CREATE VIEW nome AS SELECT ...', 'A view encapsula JOINs e GROUP BY.', 'Depois, consultar é simples: SELECT * FROM vw_faturamento_regional.'],
    courseRefs: ['ddl-create-view'],
    evidence: 'Evidência 12: View vw_faturamento_regional criada. O dashboard do CFO agora consulta "SELECT * FROM vw_faturamento_regional" — simples e rápido.',
    explanation: 'Views são queries salvas como objetos. Encapsulam lógica complexa e oferecem interface simples para BI/dashboards.',
  },
  // ═══════════════════════════════════════════
  // FASE 6: Auditoria e Performance (missões 13-14)
  // ═══════════════════════════════════════════
  {
    id: 13,
    title: 'Fase 6 — Performance: Criar Índices nas FKs',
    concept: 'EXPLAIN QUERY PLAN + CREATE INDEX',
    briefing: `O DW ficou lento no fechamento do mês. Use EXPLAIN QUERY PLAN para ver o custo, depois crie índices nas FKs mais usadas da fct_vendas para acelerar.`,
    objective: 'Crie índices nas colunas regiao_id, tempo_id e cliente_id da fct_vendas para acelerar consultas de filtro e JOIN.',
    tables: ['fct_vendas'],
    expectedColumns: ['idx_name'],
    referenceQuery: "CREATE INDEX idx_fct_regiao ON fct_vendas(regiao_id);",
    executionMode: 'ddl',
    requiredConcepts: ['create index'],
    hints: ['CREATE INDEX nome ON tabela(coluna).', 'Índices nas FKs aceleram JOINs e WHERE.', 'Crie um índice para cada coluna: regiao_id, tempo_id, cliente_id.'],
    courseRefs: ['performance-indexes'],
    evidence: 'Evidência 13: Índices criados na fct_vendas. O plano de execução muda de "SCAN" (varredura completa) para "SEARCH USING INDEX" (busca direta).',
    explanation: 'Índices criam estruturas de busca que evitam varrer a tabela inteira. Trade-off: aceleram leitura, desaceleram escrita.',
  },
  {
    id: 14,
    title: 'Fase 6 — Auditoria: Trigger de Log',
    concept: 'CREATE TRIGGER',
    briefing: `Última missão: crie um trigger que registra automaticamente toda alteração na fct_vendas no log_auditoria. Governança de dados é essencial em produção.`,
    objective: 'Crie o trigger trg_audit_fct_vendas que, após UPDATE na fct_vendas, insere um registro no log_auditoria com tabela, operação, registro_id, valor_antigo e valor_novo.',
    tables: ['fct_vendas', 'log_auditoria'],
    expectedColumns: ['trigger_name'],
    referenceQuery: "CREATE TRIGGER trg_audit_fct_vendas AFTER UPDATE ON fct_vendas FOR EACH ROW BEGIN INSERT INTO log_auditoria (tabela_afetada, operacao, registro_id, valor_antigo, valor_novo) VALUES ('fct_vendas', 'UPDATE', OLD.id, OLD.valor_total, NEW.valor_total); END;",
    executionMode: 'ddl',
    requiredConcepts: ['create trigger'],
    hints: ['CREATE TRIGGER nome AFTER UPDATE ON tabela.', 'OLD e NEW referenciam os valores antes/depois.', 'FOR EACH ROW executa para cada linha alterada.'],
    courseRefs: ['triggers'],
    evidence: 'Evidência 14: Trigger de auditoria ativo. Toda alteração na fct_vendas agora é registrada automaticamente no log_auditoria com data/hora. Governança implementada!',
    explanation: 'Triggers executam SQL automaticamente em resposta a eventos (INSERT/UPDATE/DELETE). São essenciais para auditoria e integridade.',
  },
];

export function getLevel(id) { return LEVELS.find(level => level.id === id); }
export function getTotalLevels() { return LEVELS.length; }
