/**
 * Caso 006 — "TechBrasil: Sua Primeira Semana como Analista de Dados"
 * 6 fases: OLTP (1-2), Limpeza (3-4), ETL (5-6), Star Schema (7-9), OLAP (10-12), Auditoria (13-14)
 */

export const CASE_INTRO = {
  title: 'Sua Primeira Semana como Analista de Dados',
  subtitle: 'Caso #006 — OLTP, ETL e Data Warehouse',
  story: `Parabéns pela promoção! Você agora é Analista de Dados Jr da TechBrasil. Sua primeira semana: construir o Data Warehouse da empresa. O modelo OLTP que você normalizou no Caso 005 está no ar. Agora é hora de copiar os dados para um DW otimizado para análise, criar o star schema e entregar relatórios para a diretoria. O CFO está esperando.`,
  mission: 'Construa o DW completo: OLTP → Limpeza → ETL → Star Schema → OLAP → Auditoria.',
};

export const CASE_CONCLUSION = {
  title: 'DW Operacional!',
  story: `Incrível! Você construiu o Data Warehouse completo da TechBrasil: explorou o OLTP, limpou dados sujos, montou o ETL, criou o star schema, entregou uma view ao CFO, indexou uma consulta crítica e implantou auditoria por trigger. O certificado de "Analista de BI" está pronto para download. Bem-vindo à próxima fase da sua carreira!`,
  cargo: 'Analista de BI',
  nextSteps: 'Certificado de Analista de BI disponível para download.',
};

export const DATABASE_ANALYSIS = {
  title: 'O Pipeline de Dados',
  summary: 'O DW da TechBrasil segue o pipeline: OLTP (modelo normalizado) → Staging (dados sujos) → ETL (limpeza + carga) → Star Schema (dimensões + fatos) → OLAP (views de relatório) → Auditoria (índices + triggers). Cada fase tem seu propósito.',
  entities: [
    { name: 'OLTP (clientes, produtos, vendas, itens_venda)', role: 'Sistema transacional normalizado (3FN). Fonte dos dados.', key: 'PKs + FKs', relations: ['Fonte do ETL'] },
    { name: 'Staging (stg_clientes, stg_vendas)', role: 'Área de preparação com dados sujos (espaços, vírgulas, NULLs).', key: 'PK id', relations: ['Entrada do ETL'] },
    { name: 'Dimensões (dim_*)', role: 'Tabelas de contexto: quem, o quê, onde, quando.', key: 'PK id', relations: ['FKs da fct_vendas'] },
    { name: 'Fato (fct_vendas)', role: 'Tabela central na granularidade de item vendido, com quantidade e valor.', key: 'PK id + UNIQUE (source_venda_id, produto_id)', relations: ['FKs → todas as dimensões'] },
    { name: 'Views (vw_*)', role: 'Relatórios prontos para o BI/dashboard.', key: '—', relations: ['SELECT sobre fct + dims'] },
    { name: 'log_auditoria', role: 'Trilha de auditoria via triggers.', key: 'PK id', relations: ['Preenchida automaticamente por triggers'] },
  ],
  decisions: [
    { title: 'Separar OLTP de OLAP', explanation: 'O OLTP é otimizado para escrita (transações). O DW é otimizado para leitura (análise). Separá-los evita conflito de recursos.' },
    { title: 'Limpar antes de carregar', explanation: 'Dados sujos no staging contaminam o DW. Transformações como TRIM, CAST e REPLACE devem ocorrer antes da carga no destino.' },
    { title: 'Star schema para análise', explanation: 'Fatos no centro, dimensões ao redor. Minimiza JOINs e acelera consultas analíticas.' },
    { title: 'Views reutilizáveis', explanation: 'Views encapsulam queries complexas em objetos reutilizáveis para dashboards e relatórios.' },
  ],
  checkpoints: [
    { question: 'Por que não rodar queries analíticas direto no OLTP?', answer: 'O OLTP é otimizado para transações rápidas. Queries pesadas de análise competem com as operações do dia a dia e deixam o sistema lento.' },
    { question: 'Qual a diferença entre uma dimensão e uma tabela de fato?', answer: 'Dimensão = contexto (quem, o quê, onde, quando). Fato = métrica (quanto, quantos). A fato tem FKs para as dimensões.' },
    { question: 'Para que serve um índice?', answer: 'Índices aceleram consultas de leitura permitindo ao banco encontrar registros sem varrer a tabela inteira. Trade-off: desaceleram escrita.' },
  ],
};

export const GAMEPLAY = {
  timeline: {
    bonusPoints: 200,
    events: [
      { id: 'fase-01', unlockedByMission: 2, sortKey: '2024-03-01T09:00:00', type: 'fase', label: 'Fase 1: OLTP explorado' },
      { id: 'fase-02', unlockedByMission: 4, sortKey: '2024-03-01T11:00:00', type: 'fase', label: 'Fase 2: Regras de limpeza validadas' },
      { id: 'fase-03', unlockedByMission: 6, sortKey: '2024-03-01T14:00:00', type: 'fase', label: 'Fase 3: Dimensão carregada e incremento preparado' },
      { id: 'fase-04', unlockedByMission: 9, sortKey: '2024-03-02T09:00:00', type: 'fase', label: 'Fase 4: Star schema carregado e dimensão atualizada' },
      { id: 'fase-05', unlockedByMission: 12, sortKey: '2024-03-02T14:00:00', type: 'fase', label: 'Fase 5: Consultas OLAP e view entregues' },
      { id: 'fase-06', unlockedByMission: 14, sortKey: '2024-03-03T09:00:00', type: 'fase', label: 'Fase 6: DW indexado e auditado' },
    ],
  },
  finalChallenge: {
    type: 'confrontation',
    suspectName: 'Diretoria TechBrasil',
    requiredMission: 14,
    steps: [
      { statement: 'Por que não usamos o OLTP diretamente para relatórios?', evidenceId: 'fase-01', successMessage: 'O OLTP é otimizado para transações. Queries analíticas pesadas competem com as operações do dia a dia.' },
      { statement: 'Como você garantiu a qualidade dos dados antes de carregar?', evidenceId: 'fase-02', successMessage: 'TRIM e LOWER padronizaram nomes; REPLACE e CAST converteram preços textuais em números.' },
      { statement: 'Qual a estrutura do star schema que você montou?', evidenceId: 'fase-04', successMessage: 'fct_vendas no centro com FKs para dim_tempo, dim_clientes, dim_produtos, dim_vendedores e dim_regioes.' },
      { statement: 'Como otimizou e auditou o DW?', evidenceId: 'fase-06', successMessage: 'Um índice na FK regiao_id acelera o relatório regional, e o trigger registra alterações na tabela fato.' },
    ],
  },
};

// O pipeline deve avançar na ordem: staging → dimensões → fato → consumo.
export const SEQUENTIAL_MISSIONS = true;

export const LEVELS = [
  // ═══════════════════════════════════════════
  // FASE 1: OLTP (missões 1-2)
  // ═══════════════════════════════════════════
  {
    id: 1,
    title: 'Fase 1 — Explorar o OLTP: Vendas por Mês',
    concept: 'GROUP BY + agregação',
    briefing: `Primeiro dia: conheça o modelo OLTP que você construiu no Caso 005. A diretoria quer saber o faturamento mensal. Agrupe as vendas por mês e some os valores.`,
    objective: 'Retorne o mês (data_venda) e o faturamento total (soma de valor_total) por mês, ordenado por mês.',
    tables: ['vendas'],
    expectedColumns: ['mes', 'faturamento'],
    referenceQuery: "SELECT strftime('%Y-%m', data_venda) AS mes, SUM(valor_total) AS faturamento FROM vendas GROUP BY strftime('%Y-%m', data_venda) ORDER BY mes;",
    requiredConcepts: ['group by', 'sum'],
    hints: ['Use strftime("%Y-%m", data_venda) para extrair o mês.', 'Use SUM(valor_total) para agregar.', 'GROUP BY o mês extraído.'],
    courseRefs: ['oltp-olap', 'aggregation-groupby'],
    evidence: 'Evidência 1: Faturamento mensal calculado a partir do modelo OLTP normalizado.',
    explanation: 'GROUP BY agrupa linhas por valor e SUM agrega os valores dentro de cada grupo. strftime extrai o ano-mês da data.',
  },
  {
    id: 2,
    title: 'Fase 1 — Explorar o OLTP: Top Produtos',
    concept: 'JOIN + ORDER BY + LIMIT',
    briefing: `Agora cruze vendas com produtos para descobrir os mais vendidos. O JOIN liga itens_venda com produtos pelo produto_id.`,
    objective: 'Retorne o nome do produto, a quantidade total vendida e a receita total, ordenados por quantidade (desc), top 5.',
    tables: ['itens_venda', 'produtos'],
    expectedColumns: ['produto', 'total_vendido', 'receita'],
    referenceQuery: "SELECT p.nome AS produto, SUM(iv.quantidade) AS total_vendido, SUM(iv.quantidade * iv.preco_unitario) AS receita FROM itens_venda iv JOIN produtos p ON iv.produto_id = p.id GROUP BY p.id, p.nome ORDER BY total_vendido DESC LIMIT 5;",
    requiredConcepts: ['join', 'order by', 'limit'],
    hints: ['Use JOIN para ligar itens_venda com produtos.', 'GROUP BY produto para agregar.', 'ORDER BY total_vendido DESC LIMIT 5 para o top.'],
    courseRefs: ['oltp-olap', 'joins-inner-left'],
    evidence: 'Evidência 2: Top produtos identificados por volume de vendas e receita.',
    explanation: 'JOIN recompõe o contexto entre tabelas normalizadas. GROUP BY + SUM agregam as métricas por produto.',
  },
  // ═══════════════════════════════════════════
  // FASE 2: Limpeza de Dados (missões 3-4)
  // ═══════════════════════════════════════════
  {
    id: 3,
    title: 'Fase 2 — Limpeza: Corrigir Nomes e Espaços',
    concept: 'TRIM + UPPER/LOWER',
    briefing: `O staging está sujo: nomes com espaços extras (" José "), caixa inconsistente ("ana pereira", "CARLOS"). Use TRIM e funções de caixa para padronizar.`,
    objective: 'Liste os nomes dos clientes do staging limpos: sem espaços extras e padronizados para minúsculas.',
    tables: ['stg_clientes'],
    expectedColumns: ['nome_limpo'],
    referenceQuery: "SELECT TRIM(LOWER(nome)) AS nome_limpo FROM stg_clientes ORDER BY id;",
    requiredConcepts: ['trim', 'lower'],
    hints: ['TRIM remove espaços do início e fim.', 'LOWER padroniza para minúsculas.', 'Combine TRIM(LOWER(nome)) para limpar e padronizar.'],
    courseRefs: ['data-quality', 'string-functions'],
    evidence: 'Evidência 3: Nomes limpos e padronizados para o DW.',
    explanation: 'TRIM remove espaços, LOWER/UPPER padronizam caixa. Funções de string são essenciais para data quality.',
  },
  {
    id: 4,
    title: 'Fase 2 — Limpeza: Corrigir Preços com Vírgula',
    concept: 'REPLACE + CAST',
    briefing: `Os preços no staging vêm como texto com vírgula decimal ("3.500,00"). O DW precisa de números REAL. Use REPLACE para remover ponto de milhar, trocar vírgula por ponto, e CAST para converter.`,
    objective: 'Converta os preços do staging para REAL: remova pontos de milhar, troque vírgula por ponto decimal, e caste para REAL.',
    tables: ['stg_vendas'],
    expectedColumns: ['preco_limpo'],
    referenceQuery: "SELECT CAST(REPLACE(REPLACE(TRIM(preco_venda), '.', ''), ',', '.') AS REAL) AS preco_limpo FROM stg_vendas ORDER BY id;",
    requiredConcepts: ['replace', 'cast'],
    hints: ['REPLACE(texto, ".", "") remove milhar.', 'REPLACE(resultado, ",", ".") troca vírgula por ponto.', 'CAST(... AS REAL) converte para número.'],
    courseRefs: ['data-quality', 'string-functions'],
    evidence: 'Evidência 4: Preços convertidos para REAL prontos para cálculos no DW.',
    explanation: 'REPLACE encadeado remove formatação brasileira. CAST transforma texto em número. Sem isso, agregações podem produzir valores incorretos.',
  },
  // ═══════════════════════════════════════════
  // FASE 3: ETL (missões 5-6)
  // ═══════════════════════════════════════════
  {
    id: 5,
    title: 'Fase 3 — ETL: Carga de Dimensão (clientes)',
    concept: 'INSERT INTO ... SELECT',
    briefing: `Carga total: popule dim_clientes diretamente do staging, aplicando a limpeza durante o INSERT INTO ... SELECT. Neste laboratório, preserve também o id da origem para manter o vínculo com o OLTP.`,
    objective: 'Insira na dim_clientes id, nome limpo (TRIM + LOWER), endereco e cidade a partir do staging.',
    tables: ['stg_clientes', 'dim_clientes'],
    expectedColumns: ['id', 'nome', 'endereco', 'cidade'],
    referenceQuery: "INSERT INTO dim_clientes (id, nome, endereco, cidade) SELECT id, TRIM(LOWER(nome)), endereco, cidade FROM stg_clientes;",
    verificationQuery: 'SELECT id, nome, endereco, cidade FROM dim_clientes ORDER BY id;',
    expectedResultQuery: 'SELECT id, nome, endereco, cidade FROM dim_clientes ORDER BY id;',
    expectedRows: 9,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'trim', 'lower'],
    hints: ['Use INSERT INTO dim_clientes (id, nome, endereco, cidade) SELECT ... FROM stg_clientes.', 'TRIM remove espaços e LOWER padroniza a caixa.', 'Preserve o id de origem para manter as FKs do OLTP.'],
    courseRefs: ['etl', 'dml-insert', 'string-functions'],
    evidence: 'Evidência 5: dim_clientes populada com 9 registros limpos, IDs preservados e cidades válidas.',
    explanation: 'INSERT INTO ... SELECT combina transformação e carga. Neste modelo didático, preservar a chave da origem simplifica o vínculo entre OLTP e dimensão.',
  },
  {
    id: 6,
    title: 'Fase 3 — ETL: Identificar Carga Incremental',
    concept: 'WHERE NOT EXISTS + transformação',
    briefing: `Antes de carregar, identifique os itens do staging que ainda não existem na fato. Use WHERE NOT EXISTS pela combinação venda de origem + produto e transforme quantidade e preço na própria consulta.`,
    objective: 'Liste source_venda_id, quantidade, valor_unitario e valor_total apenas para itens do staging ainda ausentes da fct_vendas.',
    tables: ['stg_vendas', 'fct_vendas'],
    expectedColumns: ['source_venda_id', 'quantidade', 'valor_unitario', 'valor_total'],
    referenceQuery: "SELECT s.id AS source_venda_id, CAST(s.quantidade AS INTEGER) AS quantidade, CAST(REPLACE(REPLACE(TRIM(s.preco_venda), '.', ''), ',', '.') AS REAL) AS valor_unitario, CAST(s.quantidade AS INTEGER) * CAST(REPLACE(REPLACE(TRIM(s.preco_venda), '.', ''), ',', '.') AS REAL) AS valor_total FROM stg_vendas s WHERE NOT EXISTS (SELECT 1 FROM fct_vendas f JOIN dim_produtos p ON p.id = f.produto_id WHERE f.source_venda_id = s.id AND p.nome = TRIM(s.produto_nome)) ORDER BY s.id;",
    requiredConcepts: ['not exists', 'cast'],
    hints: ['Correlacione NOT EXISTS por source_venda_id e pelo produto do staging.', 'Converta quantidade e preço com CAST.', 'Multiplique quantidade × preço para obter valor_total.'],
    courseRefs: ['etl', 'cte-subqueries'],
    evidence: 'Evidência 6: Cinco registros incrementais foram identificados e transformados sem poluir a tabela fato com chaves fictícias.',
    explanation: 'WHERE NOT EXISTS é um padrão de carga incremental: seleciona somente chaves ainda ausentes do destino antes da etapa de escrita.',
  },
  // ═══════════════════════════════════════════
  // FASE 4: Star Schema (missões 7-9)
  // ═══════════════════════════════════════════
  {
    id: 7,
    title: 'Fase 4 — Star Schema: Popular Dimensão Tempo',
    concept: 'INSERT INTO (dimensão)',
    briefing: `Produtos, vendedores e regiões já foram carregados pela equipe. Complete o star schema populando dim_tempo com as datas do OLTP; cada linha deve representar uma data única.`,
    objective: 'Insira na dim_tempo as datas únicas das vendas com ano, mês e dia extraídos.',
    tables: ['vendas', 'dim_tempo'],
    expectedColumns: ['data_completa', 'ano', 'mes', 'dia'],
    referenceQuery: 'INSERT INTO dim_tempo (data_completa, ano, mes, dia) SELECT DISTINCT data_venda, CAST(strftime("%Y", data_venda) AS INTEGER), CAST(strftime("%m", data_venda) AS INTEGER), CAST(strftime("%d", data_venda) AS INTEGER) FROM vendas;',
    verificationQuery: 'SELECT data_completa, ano, mes, dia FROM dim_tempo ORDER BY data_completa;',
    expectedResultQuery: 'SELECT data_completa, ano, mes, dia FROM dim_tempo ORDER BY data_completa;',
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'distinct'],
    hints: ['Use INSERT INTO dim_tempo (data_completa, ano, mes, dia) SELECT DISTINCT ...', 'strftime extrai ano, mês e dia.', 'CAST para INTEGER.'],
    courseRefs: ['star-schema', 'dml-insert'],
    evidence: 'Evidência 7: dim_tempo populada com datas únicas. A dimensão tempo permite análise temporal.',
    explanation: 'Dimensões descrevem o contexto (quando, onde, quem). A dim_tempo é essencial para análise de tendências e comparativos.',
  },
  {
    id: 8,
    title: 'Fase 4 — Star Schema: Popular a Tabela de Fatos',
    concept: 'INSERT INTO (fato)',
    briefing: `A fct_vendas é o centro do star schema. Cada linha representa um item de venda e é identificada na origem pela combinação source_venda_id + produto_id. Carregue métricas e FKs para todas as dimensões.`,
    objective: 'Insira na fct_vendas source_venda_id, as FKs de tempo, cliente, produto, vendedor e região, além de quantidade, valor_unitario e valor_total.',
    tables: ['vendas', 'itens_venda', 'vendedores', 'dim_tempo', 'fct_vendas'],
    expectedColumns: ['source_venda_id', 'tempo_id', 'cliente_id', 'produto_id', 'vendedor_id', 'regiao_id', 'quantidade', 'valor_unitario', 'valor_total'],
    referenceQuery: "INSERT INTO fct_vendas (source_venda_id, tempo_id, cliente_id, produto_id, vendedor_id, regiao_id, quantidade, valor_unitario, valor_total) SELECT v.id, t.id, v.cliente_id, iv.produto_id, v.vendedor_id, ve.regiao_id, iv.quantidade, iv.preco_unitario, iv.quantidade * iv.preco_unitario FROM itens_venda iv JOIN vendas v ON iv.venda_id = v.id JOIN vendedores ve ON ve.id = v.vendedor_id JOIN dim_tempo t ON t.data_completa = v.data_venda;",
    verificationQuery: 'SELECT source_venda_id, tempo_id, cliente_id, produto_id, vendedor_id, regiao_id, quantidade, valor_unitario, valor_total FROM fct_vendas ORDER BY source_venda_id, produto_id;',
    expectedResultQuery: 'SELECT source_venda_id, tempo_id, cliente_id, produto_id, vendedor_id, regiao_id, quantidade, valor_unitario, valor_total FROM fct_vendas ORDER BY source_venda_id, produto_id;',
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'join'],
    hints: ['Use source_venda_id + produto_id para preservar a granularidade do item.', 'Faça JOIN de itens_venda, vendas, vendedores e dim_tempo.', 'valor_total = quantidade × preco_unitario.'],
    courseRefs: ['star-schema', 'dml-insert', 'joins-inner-left'],
    evidence: 'Evidência 8: fct_vendas populada com 20 linhas (1 por item de venda). Granularidade: item de venda.',
    explanation: 'A tabela de fatos contém métricas e FKs para dimensões. Granularidade = nível de detalhe (aqui: item de venda).',
  },
  {
    id: 9,
    title: 'Fase 4 — Star Schema: SCD Type 1 (Atualizar Vendedor)',
    concept: 'UPDATE (SCD Type 1)',
    briefing: `O vendedor "R. Souza" foi cadastrado como "Rodrigo Souza" no RH. Atualize a dimensão sem alterar as linhas da tabela fato. Isso é SCD Type 1: o valor anterior da dimensão é sobrescrito e os relatórios passam a exibir o nome atual.`,
    objective: 'Atualize o nome do vendedor id=2 na dim_vendedores para "Rodrigo Souza" (SCD Type 1).',
    tables: ['dim_vendedores'],
    expectedColumns: ['id', 'nome'],
    referenceQuery: "UPDATE dim_vendedores SET nome = 'Rodrigo Souza' WHERE id = 2;",
    verificationQuery: 'SELECT id, nome FROM dim_vendedores WHERE id = 2;',
    expectedResultQuery: 'SELECT id, nome FROM dim_vendedores WHERE id = 2;',
    expectedRows: 1,
    executionMode: 'ddl',
    requiredConcepts: ['update'],
    hints: ['Use UPDATE ... SET ... WHERE.', 'SCD Type 1 sobrescreve o valor atual.', 'As linhas da fato não mudam, mas relatórios passam a exibir o nome atual da dimensão.'],
    courseRefs: ['star-schema', 'dml-select-where'],
    evidence: 'Evidência 9: Vendedor atualizado na dimensão. As FKs históricas da fct_vendas permanecem válidas e passam a apontar para o nome atual.',
    explanation: 'SCD Type 1 (Slowly Changing Dimension): atualiza o valor atual sem preservar o anterior. Útil quando o histórico não importa.',
  },
  // ═══════════════════════════════════════════
  // FASE 5: OLAP (missões 10-12)
  // ═══════════════════════════════════════════
  {
    id: 10,
    title: 'Fase 5 — OLAP: Faturamento por Região',
    concept: 'GROUP BY + JOIN múltiplo',
    briefing: `O CFO quer o faturamento por região. Cruze fct_vendas com dim_regioes pelo regiao_id e agregue.`,
    objective: 'Retorne o nome da região e o faturamento total (soma de valor_total), agrupado por região, ordenado por faturamento (desc).',
    tables: ['fct_vendas', 'dim_regioes'],
    expectedColumns: ['regiao', 'faturamento'],
    referenceQuery: "SELECT r.nome AS regiao, SUM(f.valor_total) AS faturamento FROM fct_vendas f JOIN dim_regioes r ON f.regiao_id = r.id GROUP BY r.id, r.nome ORDER BY faturamento DESC;",
    requiredConcepts: ['join', 'group by', 'sum'],
    hints: ['JOIN fct_vendas com dim_regioes pelo regiao_id.', 'GROUP BY região para agregar.', 'SUM(valor_total) para o faturamento.'],
    courseRefs: ['olap-bi', 'aggregation-groupby'],
    evidence: 'Evidência 10: Faturamento por região calculado via star schema com apenas 1 JOIN.',
    explanation: 'O star schema simplifica o consumo analítico: fato + dimensão de região resolvem este indicador sem percorrer várias entidades operacionais.',
  },
  {
    id: 11,
    title: 'Fase 5 — OLAP: Comparativo Mensal com LAG',
    concept: 'Window Function (LAG)',
    briefing: `O CFO quer comparar o faturamento de cada mês com o anterior. Use LAG() para acessar o valor da linha anterior sem self-join.`,
    objective: 'Retorne o mês, faturamento do mês e faturamento do mês anterior (usando LAG), ordenado por mês.',
    tables: ['fct_vendas', 'dim_tempo'],
    expectedColumns: ['mes', 'faturamento_mes', 'faturamento_anterior'],
    referenceQuery: "WITH mensal AS (SELECT t.ano, t.mes, SUM(f.valor_total) AS faturamento_mes FROM fct_vendas f JOIN dim_tempo t ON f.tempo_id = t.id GROUP BY t.ano, t.mes) SELECT printf('%04d-%02d', ano, mes) AS mes, faturamento_mes, LAG(faturamento_mes) OVER (ORDER BY ano, mes) AS faturamento_anterior FROM mensal ORDER BY ano, mes;",
    requiredConcepts: ['with', 'group by', 'lag', 'over'],
    hints: ['LAG(coluna) OVER (ORDER BY ...) acessa a linha anterior.', 'Combine com GROUP BY para agregar por mês primeiro.', 'O ORDER BY dentro do OVER define a ordem da janela.'],
    courseRefs: ['olap-bi', 'window-functions', 'cte-subqueries'],
    evidence: 'Evidência 11: Comparativo mensal com LAG — o faturamento do mês anterior aparece ao lado.',
    explanation: 'LAG é uma window function que acessa o valor de N linhas antes na janela definida por OVER (ORDER BY ...). Evita self-join.',
  },
  {
    id: 12,
    title: 'Fase 5 — OLAP: Criar View para o Dashboard do CFO',
    concept: 'CREATE VIEW',
    briefing: `Entregue uma view reutilizável para o dashboard do CFO: faturamento por região e mês. A view encapsula a query complexa em um objeto simples de consultar.`,
    objective: 'Crie a view vw_faturamento_regional com região, mês, faturamento e total de itens, agrupado por região e mês.',
    tables: ['fct_vendas', 'dim_regioes', 'dim_tempo'],
    expectedColumns: ['regiao', 'mes', 'faturamento', 'total_itens'],
    referenceQuery: "CREATE VIEW vw_faturamento_regional AS SELECT r.nome AS regiao, printf('%04d-%02d', t.ano, t.mes) AS mes, SUM(f.valor_total) AS faturamento, COUNT(*) AS total_itens FROM fct_vendas f JOIN dim_regioes r ON f.regiao_id = r.id JOIN dim_tempo t ON f.tempo_id = t.id GROUP BY r.nome, t.ano, t.mes;",
    executionMode: 'create_view',
    viewName: 'vw_faturamento_regional',
    verificationQuery: 'SELECT regiao, mes, faturamento, total_itens FROM vw_faturamento_regional ORDER BY regiao, mes;',
    expectedResultQuery: "SELECT r.nome AS regiao, printf('%04d-%02d', t.ano, t.mes) AS mes, SUM(f.valor_total) AS faturamento, COUNT(*) AS total_itens FROM fct_vendas f JOIN dim_regioes r ON f.regiao_id = r.id JOIN dim_tempo t ON f.tempo_id = t.id GROUP BY r.nome, t.ano, t.mes ORDER BY regiao, mes;",
    requiredConcepts: ['create view', 'join', 'group by'],
    hints: ['Use CREATE VIEW nome AS SELECT ...', 'A view encapsula JOINs e GROUP BY.', 'Depois, consultar é simples: SELECT * FROM vw_faturamento_regional.'],
    courseRefs: ['olap-bi', 'views'],
    evidence: 'Evidência 12: View vw_faturamento_regional criada. O dashboard do CFO agora consulta "SELECT * FROM vw_faturamento_regional" — simples e rápido.',
    explanation: 'Views são queries salvas como objetos. Encapsulam lógica complexa e oferecem interface simples para BI/dashboards.',
  },
  // ═══════════════════════════════════════════
  // FASE 6: Auditoria e Performance (missões 13-14)
  // ═══════════════════════════════════════════
  {
    id: 13,
    title: 'Fase 6 — Performance: Indexar a FK de Região',
    concept: 'CREATE INDEX em chave estrangeira',
    briefing: `Consultas que filtram uma região específica ficaram lentas no fechamento do mês. Crie um índice na FK regiao_id da fct_vendas, usada nesses filtros e JOINs seletivos.`,
    objective: 'Crie o índice idx_fct_regiao na coluna regiao_id da fct_vendas.',
    tables: ['fct_vendas'],
    expectedColumns: ['idx_name', 'coluna'],
    referenceQuery: "CREATE INDEX idx_fct_regiao ON fct_vendas(regiao_id);",
    verificationQuery: "SELECT m.name AS idx_name, p.name AS coluna FROM sqlite_master m JOIN pragma_index_info(m.name) p WHERE m.type = 'index' AND m.name = 'idx_fct_regiao' ORDER BY p.seqno;",
    expectedResultQuery: "SELECT m.name AS idx_name, p.name AS coluna FROM sqlite_master m JOIN pragma_index_info(m.name) p WHERE m.type = 'index' AND m.name = 'idx_fct_regiao' ORDER BY p.seqno;",
    executionMode: 'ddl',
    requiredConcepts: ['create index'],
    hints: ['Use CREATE INDEX idx_fct_regiao ON ...', 'A tabela é fct_vendas.', 'A coluna indexada deve ser regiao_id.'],
    courseRefs: ['dw-governance', 'indexes-optimization'],
    evidence: 'Evidência 13: A FK regiao_id foi indexada e agora pode atender filtros regionais seletivos sem varrer toda a fato.',
    explanation: 'Índices criam estruturas de busca que evitam varrer a tabela inteira. Trade-off: aceleram leitura, desaceleram escrita.',
  },
  {
    id: 14,
    title: 'Fase 6 — Auditoria: Trigger de Log',
    concept: 'CREATE TRIGGER',
    briefing: `Última missão: crie um trigger que registra automaticamente toda alteração na fct_vendas no log_auditoria. Governança de dados é essencial em produção.`,
    objective: 'Crie o trigger trg_audit_fct_vendas que, após UPDATE na fct_vendas, insere um registro no log_auditoria com tabela, operação, registro_id, valor_antigo e valor_novo.',
    tables: ['fct_vendas', 'log_auditoria'],
    expectedColumns: ['trigger_name', 'tabela_afetada', 'operacao', 'registro_id', 'valor_antigo', 'valor_novo'],
    referenceQuery: "CREATE TRIGGER trg_audit_fct_vendas AFTER UPDATE ON fct_vendas FOR EACH ROW BEGIN INSERT INTO log_auditoria (tabela_afetada, operacao, registro_id, valor_antigo, valor_novo) VALUES ('fct_vendas', 'UPDATE', OLD.id, OLD.valor_total, NEW.valor_total); END;",
    exerciseQuery: 'UPDATE fct_vendas SET valor_total = valor_total + 1 WHERE id = 1;',
    verificationQuery: "SELECT m.name AS trigger_name, l.tabela_afetada, l.operacao, l.registro_id, l.valor_antigo, l.valor_novo FROM sqlite_master m CROSS JOIN log_auditoria l WHERE m.type = 'trigger' AND m.name = 'trg_audit_fct_vendas' AND m.tbl_name = 'fct_vendas' ORDER BY l.id;",
    expectedResultQuery: "SELECT m.name AS trigger_name, l.tabela_afetada, l.operacao, l.registro_id, l.valor_antigo, l.valor_novo FROM sqlite_master m CROSS JOIN log_auditoria l WHERE m.type = 'trigger' AND m.name = 'trg_audit_fct_vendas' AND m.tbl_name = 'fct_vendas' ORDER BY l.id;",
    executionMode: 'ddl',
    requiredConcepts: ['create trigger', 'after update', 'insert', 'old', 'new'],
    hints: ['CREATE TRIGGER nome AFTER UPDATE ON tabela.', 'OLD e NEW referenciam os valores antes/depois.', 'FOR EACH ROW executa para cada linha alterada.'],
    courseRefs: ['dw-governance', 'triggers', 'dml-insert'],
    evidence: 'Evidência 14: Trigger de auditoria ativo. Toda alteração na fct_vendas agora é registrada automaticamente no log_auditoria com data/hora. Governança implementada!',
    explanation: 'Triggers executam SQL automaticamente em resposta a eventos (INSERT/UPDATE/DELETE). São essenciais para auditoria e integridade.',
  },
];

export function getLevel(id) { return LEVELS.find(level => level.id === id); }
export function getTotalLevels() { return LEVELS.length; }
