/** Missões do Caso #003 — A Rota da Cripto-Ativo. */
const mission = (id, title, concept, objective, tables, expectedColumns, referenceQuery, requiredConcepts, hints, evidence, explanation, courseRefs) => ({ id, title, concept, briefing: `Siga o dinheiro na blockchain. ${objective}`, objective, tables, expectedColumns, referenceQuery, requiredConcepts, hints, evidence, explanation, courseRefs });
export const CASE_INTRO = { title: 'A Rota da Cripto-Ativo', subtitle: 'Caso #003 — Lavagem de Dinheiro e Pulverização', story: 'O dinheiro roubado foi rastreado até uma corretora de criptomoedas. O fraudador fragmentou valores em microtransferências para fugir dos alertas.', mission: 'Resolva 10 missões e encontre a carteira da rede.' };
export const DATABASE_ANALYSIS = {
  title: 'Uma rede de carteiras, transferências e identidades',
  summary: 'Carteiras representam participantes; transferências representam eventos entre duas carteiras. Exchanges e registros KYC ficam separados para que regulamentação, identidade e fluxo financeiro possam ser analisados de forma independente.',
  entities: [
    { name: 'carteiras', role: 'Nós da rede financeira, com endereço, titular e exchange.', key: 'PK id', relations: ['exchange → exchanges.id'] },
    { name: 'transferencias', role: 'Arestas cronológicas entre uma origem e um destino.', key: 'PK id', relations: ['carteira_origem_id / carteira_destino_id → carteiras.id'] },
    { name: 'exchanges', role: 'Corretoras e seu estado regulatório.', key: 'PK id', relations: [] },
    { name: 'kyc_registros', role: 'Comprova quando uma carteira passou por verificação de identidade.', key: 'PK id', relations: ['carteira_id → carteiras.id'] },
  ],
  decisions: [
    { title: 'Origem e destino usam a mesma entidade', explanation: 'Duas FKs para carteiras expressam papéis diferentes sem duplicar o cadastro da carteira.' },
    { title: 'Transferência é evento imutável', explanation: 'Cada movimentação recebe sua própria linha, permitindo ordenar, contar e calcular intervalos ou acumulados.' },
    { title: 'KYC opcional permanece separado', explanation: 'A ausência de correspondência passa a ser uma evidência consultável com LEFT JOIN e IS NULL.' },
  ],
  checkpoints: [
    { question: 'Por que carteiras não têm colunas transferencia_1, transferencia_2 e assim por diante?', answer: 'A quantidade de eventos é variável. Uma relação um-para-muitos em transferencias cresce por linhas e continua consultável.' },
    { question: 'Como representar a falta de KYC sem gravar texto duplicado?', answer: 'Mantemos kyc_registros separado; uma carteira sem linha correspondente é detectada com LEFT JOIN e IS NULL.' },
  ],
};
export const CASE_CONCLUSION = { title: 'Rede Desmascarada', story: 'A carteira 0xAF7...3B2, de Marcos Duarte, recebeu 47 microtransferências em 72 horas através da exchange não regulamentada ShadowX. A identidade não possui KYC.', nextSteps: 'O Caso #004 foi desbloqueado.' };
export const LEVELS = [
  mission(1,'As Carteiras','SELECT','Liste endereço e titular de todas as carteiras.',['carteiras'],['endereco_hash','titular'],'SELECT endereco_hash, titular FROM carteiras ORDER BY id;',['select'],['Use a tabela carteiras.','Selecione as duas colunas pedidas.','SELECT endereco_hash, titular FROM carteiras;'],'As carteiras revelam os participantes da rota.','SELECT define as colunas retornadas.',['sql-intro']),
  mission(2,'Abaixo do Radar','WHERE','Liste transferências abaixo de 0,02 BTC.',['transferencias'],['id','valor_btc'],'SELECT id, valor_btc FROM transferencias WHERE valor_btc < 0.02 ORDER BY id;',['where'],['Use WHERE no valor.','Compare valor_btc com 0.02.','WHERE valor_btc < 0.02'],'As microtransferências evitam limiares de alerta.','WHERE filtra as linhas.',['dml-select-where']),
  mission(3,'A Cadência Suspeita','ORDER BY + datas','Liste data e hash das transferências ordenadas da mais antiga para a mais recente.',['transferencias'],['data_hora','hash_transacao'],'SELECT data_hora, hash_transacao FROM transferencias ORDER BY data_hora ASC;',['order by'],['Use data_hora para ordenar.','ASC é a ordem cronológica.','ORDER BY data_hora ASC'],'A sequência mostra uma cadência automatizada.','ORDER BY organiza a linha do tempo.',['having-where-orderby-like']),
  mission(4,'Origem e Destino','JOIN','Mostre origem, destino e valor de cada transferência.',['transferencias','carteiras'],['origem','destino','valor_btc'],'SELECT co.endereco_hash AS origem, cd.endereco_hash AS destino, t.valor_btc FROM transferencias t JOIN carteiras co ON co.id = t.carteira_origem_id JOIN carteiras cd ON cd.id = t.carteira_destino_id ORDER BY t.id;',['join'],['A tabela carteiras é usada duas vezes.','Dê aliases diferentes para origem e destino.','JOIN carteiras co ... JOIN carteiras cd ...'],'A mesma carteira destino recebe transferências repetidas.','JOIN pode ligar uma tabela a ela mesma por aliases.',['joins-inner-left']),
  mission(5,'Pulverização','GROUP BY + COUNT + SUM','Encontre origens com mais de 10 transferências, incluindo quantidade e total.',['transferencias'],['carteira_origem_id','quantidade','total_btc'],'SELECT carteira_origem_id, COUNT(*) AS quantidade, SUM(valor_btc) AS total_btc FROM transferencias GROUP BY carteira_origem_id HAVING COUNT(*) > 10 ORDER BY carteira_origem_id;',['group by','count','sum'],['Agrupe por carteira_origem_id.','Conte linhas e some valor_btc.','Filtre grupos acima de 10.'],'A carteira de origem disparou dezenas de operações.','Agregações expõem volume e frequência.',['aggregation-groupby']),
  mission(6,'A Janela de Tempo','ROW_NUMBER()','Numere as transferências de cada origem em ordem cronológica.',['transferencias'],['carteira_origem_id','data_hora','sequencia'],'SELECT carteira_origem_id, data_hora, ROW_NUMBER() OVER (PARTITION BY carteira_origem_id ORDER BY data_hora) AS sequencia FROM transferencias ORDER BY carteira_origem_id, data_hora;',['row_number'],['ROW_NUMBER usa OVER.', 'PARTITION BY reinicia a contagem por origem.', 'Ordene a janela por data_hora.'],'A numeração torna visível a longa sequência da carteira suspeita.','ROW_NUMBER numera linhas dentro de uma janela.',['window-functions']),
  mission(7,'O Intervalo Revelador','LAG()','Mostre cada transferência e a data da transferência anterior da mesma origem.',['transferencias'],['carteira_origem_id','data_hora','anterior'],'SELECT carteira_origem_id, data_hora, LAG(data_hora) OVER (PARTITION BY carteira_origem_id ORDER BY data_hora) AS anterior FROM transferencias ORDER BY carteira_origem_id, data_hora;',['lag'],['LAG consulta a linha anterior.', 'Particione por origem.', 'Ordene pelo horário.'],'Os intervalos curtos confirmam o padrão de smurfing.','LAG compara cada linha com a anterior.',['window-functions']),
  mission(8,'O Acúmulo','SUM() OVER','Mostre o valor acumulado de cada origem ao longo do tempo.',['transferencias'],['carteira_origem_id','data_hora','acumulado_btc'],'SELECT carteira_origem_id, data_hora, SUM(valor_btc) OVER (PARTITION BY carteira_origem_id ORDER BY data_hora) AS acumulado_btc FROM transferencias ORDER BY carteira_origem_id, data_hora;',['sum','over'],['SUM também pode ser função de janela.', 'Use OVER com PARTITION BY e ORDER BY.', 'Dê um alias ao acumulado.'],'O montante fragmentado cresce rapidamente na linha do tempo.','SUM OVER calcula um acumulado sem agrupar as linhas.',['window-functions']),
  mission(9,'Identidade Falsa','LEFT JOIN + IS NULL','Liste carteiras sem registro KYC.',['carteiras','kyc_registros'],['endereco_hash','titular'],'SELECT c.endereco_hash, c.titular FROM carteiras c LEFT JOIN kyc_registros k ON k.carteira_id = c.id WHERE k.id IS NULL ORDER BY c.id;',['left join','is null'],['LEFT JOIN preserva todas as carteiras.', 'Sem KYC, k.id será NULL.', 'Filtre com WHERE k.id IS NULL.'],'A carteira de Marcos não possui verificação de identidade.','LEFT JOIN + IS NULL encontra itens sem correspondência.',['joins-inner-left']),
  mission(10,'A Rede Desmascarada','CTE + múltiplos JOINs','Identifique a carteira não regulamentada sem KYC que recebeu mais de 40 transferências.',['carteiras','transferencias','exchanges','kyc_registros'],['endereco_hash','titular','quantidade_transferencias'],'WITH recebimentos AS (SELECT carteira_destino_id, COUNT(*) AS quantidade_transferencias FROM transferencias GROUP BY carteira_destino_id) SELECT c.endereco_hash, c.titular, r.quantidade_transferencias FROM recebimentos r JOIN carteiras c ON c.id = r.carteira_destino_id JOIN exchanges e ON e.id = c.exchange LEFT JOIN kyc_registros k ON k.carteira_id = c.id WHERE e.regulamentada = 0 AND k.id IS NULL AND r.quantidade_transferencias > 40 ORDER BY c.id;',['with','join','count'],['Crie uma CTE para contar recebimentos.', 'Junte carteira e exchange.', 'Use LEFT JOIN para verificar KYC ausente.'],'Marcos Duarte controla a carteira central da rede.','CTEs tornam investigações complexas mais legíveis.',['cte-subqueries','window-functions']),
];
export function getLevel(id) { return LEVELS.find(level => level.id === id); }
export function getTotalLevels() { return LEVELS.length; }
