/**
 * Caso 005 — "A Planilha do Inferno" (Normalização e Relacionamentos)
 * 14 missões em 4 arcos: 1FN (1-4), 2FN (5-7), 3FN (8-9), Relacionamentos (10-12), Fechamento (13-14)
 */

export const CASE_INTRO = {
  title: 'A Planilha do Inferno',
  subtitle: 'Caso #005 — Normalização e Relacionamentos',
  story: `Você foi contratado como estagiário de TI na TechBrasil. Sua primeira missão: transformar a "planilha do sistema" em um verdadeiro banco de dados. O antigo funcionário chamava orgulhosamente o arquivo supremacy.csv de "Banco de Dados Supremo". A diretoria deu um prazo. E o José da Silva já está esperando ser encontrado... de novo. E de novo.`,
  mission: 'Normalize a planilha até a 3FN e modele os relacionamentos corretos.',
};

export const CASE_CONCLUSION = {
  title: 'Modelo Entregue!',
  story: `Parabéns! Você transformou a "Planilha do Inferno" em um modelo OLTP normalizado até a 3FN, com relacionamentos PK/FK corretos. O e-mail de promoção já está na sua caixa: "Analista de Dados Jr" — bem-vindo à TechBrasil! O Caso 006 (sua primeira semana como analista) já está desbloqueado.`,
  cargo: 'Analista de Dados Jr',
  nextSteps: 'O Caso #006 — TechBrasil: Sua Primeira Semana — foi desbloqueado.',
};

export const DATABASE_ANALYSIS = {
  title: 'O Caos da Planilha',
  summary: 'A planilha supremacy mistura dados de clientes, produtos, vendedores e regiões na mesma linha. O mesmo cliente aparece de 3 formas diferentes, o endereço se repete em cada venda, e atributos de região dependem do vendedor (transitividade). Sua missão: separar cada entidade na sua tabela.',
  entities: [
    { name: 'supremacy', role: 'A planilha desnormalizada. Cada linha é uma venda, mas contém dados de 5 entidades diferentes.', key: 'PK id', relations: ['—'] },
    { name: 'clientes', role: 'Tabela alvo: identidade do cliente (nome, CPF, endereço, telefone).', key: 'PK id', relations: ['FK: vendas.cliente_id → clientes.id'] },
    { name: 'produtos', role: 'Tabela alvo: catálogo de produtos (nome, categoria, preço).', key: 'PK id', relations: ['FK: itens_venda.produto_id → produtos.id'] },
    { name: 'vendedores', role: 'Tabela alvo: dados do vendedor. Região será extraída para tabela própria (3FN).', key: 'PK id', relations: ['FK: vendas.vendedor_id → vendedores.id'] },
    { name: 'regioes', role: 'Tabela alvo: nome da região e gerente (extraída de vendedores por 3FN).', key: 'PK id', relations: ['FK: vendedores.regiao_id → regioes.id'] },
    { name: 'vendas', role: 'Tabela alvo: cabeçalho da venda (data, cliente, vendedor).', key: 'PK id', relations: ['FK: cliente_id → clientes.id', 'FK: vendedor_id → vendedores.id'] },
    { name: 'itens_venda', role: 'Tabela alvo: detalhes da venda (produto, quantidade, preço). PK composta.', key: 'PK (venda_id, produto_id)', relations: ['FK: venda_id → vendas.id', 'FK: produto_id → produtos.id'] },
  ],
  decisions: [
    { title: 'Separar entidades', explanation: 'Cada assunto (cliente, produto, vendedor, região) deve ter sua própria tabela. Isso elimina redundância e anomalias de atualização.' },
    { title: 'Definir PKs', explanation: 'Toda tabela precisa de uma chave primária que identifique cada linha de forma única.' },
    { title: 'Criar FKs', explanation: 'As chaves estrangeiras "colam" as tabelas separadas de volta, preservando os relacionamentos sem duplicar dados.' },
    { title: 'Resolver N:N', explanation: 'O relacionamento entre vendas e produtos é N:N — exige uma tabela intermediária (itens_venda) com PK composta.' },
  ],
  checkpoints: [
    { question: 'Por que o endereço do cliente se repete em 40 linhas?', answer: 'Porque a planilha não separa entidades. Na 3FN, o endereço fica só em clientes e todas as vendas referenciam pela FK.' },
    { question: 'Por que a região não pode ficar na tabela de vendedores?', answer: 'Dependência transitiva: a região depende do regiao_id, não diretamente do vendedor. Se a região muda de gerente, todos os vendedores precisam ser atualizados.' },
    { question: 'Por que precisamos da tabela itens_venda?', answer: 'O relacionamento entre vendas e produtos é N:N. A tabela intermediária resolve com PK composta (venda_id + produto_id) e duas FKs.' },
  ],
};

export const GAMEPLAY = {
  timeline: {
    bonusPoints: 150,
    events: [
      { id: 'anomalia-01', unlockedByMission: 1, sortKey: '2024-01-01T00:00:00', type: 'anomalia', label: 'Cliente repetido 3x com nomes diferentes' },
      { id: 'anomalia-02', unlockedByMission: 5, sortKey: '2024-01-02T00:00:00', type: 'anomalia', label: 'Preço do produto depende só do produto (2FN)' },
      { id: 'anomalia-03', unlockedByMission: 8, sortKey: '2024-01-03T00:00:00', type: 'anomalia', label: 'Região depende do vendedor, não da venda (3FN)' },
      { id: 'anomalia-04', unlockedByMission: 10, sortKey: '2024-01-04T00:00:00', type: 'anomalia', label: 'N:N entre vendas e produtos exige tabela intermediária' },
    ],
  },
  finalChallenge: {
    type: 'confrontation',
    suspectName: 'Diretor da TechBrasil',
    requiredMission: 14,
    steps: [
      { statement: 'Por que o cliente se repete em várias linhas da planilha?', evidenceId: 'anomalia-01', successMessage: 'A planilha não separava entidades. A 1FN resolve: cada cliente tem sua linha em clientes.' },
      { statement: 'Por que a região não pode ficar na tabela de vendedores?', evidenceId: 'anomalia-03', successMessage: 'Dependência transitiva (3FN): a região descreve a região, não o vendedor.' },
      { statement: 'O que acontece quando o José muda de endereço?', evidenceId: 'anomalia-02', successMessage: 'No modelo normalizado, 1 UPDATE em clientes resolve. No desnormalizado, seriam 4+ UPDATEs.' },
      { statement: 'Por que precisamos da tabela itens_venda?', evidenceId: 'anomalia-04', successMessage: 'Relacionamento N:N exige tabela intermediária com PK composta e duas FKs.' },
    ],
  },
};

export const LEVELS = [
  // ═══════════════════════════════════════════
  // ARCO 1: 1FN — Eliminar grupos repetidos (missões 1-4)
  // ═══════════════════════════════════════════
  {
    id: 1,
    title: 'Arco 1FN — Identificar Clientes Únicos',
    concept: 'DISTINCT + TRIM',
    briefing: `Primeiro passo: extrair os clientes únicos da planilha. O mesmo cliente aparece de 3 formas diferentes ("José da Silva", "jose da silva", "J. da Silva"). Use DISTINCT para eliminar duplicatas e TRIM para remover espaços.`,
    objective: 'Liste os nomes únicos de clientes da planilha supremacy, ordenados alfabeticamente.',
    tables: ['supremacy'],
    expectedColumns: ['nome'],
    referenceQuery: "SELECT DISTINCT TRIM(cliente_nome) AS nome FROM supremacy ORDER BY nome;",
    requiredConcepts: ['distinct'],
    hints: ['Use DISTINCT para eliminar duplicatas.', 'Use TRIM() para remover espaços extras.', "SELECT DISTINCT TRIM(cliente_nome) AS nome FROM supremacy ORDER BY nome;"],
    courseRefs: ['dml-select-where'],
    evidence: 'Evidência 1: A planilha tem clientes únicos que precisam ser extraídos.',
    explanation: 'DISTINCT elimina linhas duplicadas. TRIM() remove espaços extras do início e fim do texto.',
  },
  {
    id: 2,
    title: 'Arco 1FN — Popular Tabela de Clientes',
    concept: 'INSERT INTO ... SELECT',
    briefing: `A tabela clientes já existe (vazia). Agora preencha-a com os dados únicos extraídos da planilha. Use INSERT INTO ... SELECT com GROUP BY para garantir uma linha por cliente.`,
    objective: 'Insira na tabela clientes os nomes, CPFs, endereços e telefones únicos da planilha supremacy.',
    tables: ['supremacy', 'clientes'],
    expectedColumns: ['id', 'nome', 'cpf', 'endereco', 'telefone'],
    referenceQuery: "INSERT INTO clientes (nome, cpf, endereco, telefone) SELECT TRIM(cliente_nome), cliente_cpf, cliente_endereco, cliente_telefone FROM supremacy GROUP BY cliente_nome;",
    expectedRows: 9,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'group by'],
    hints: ['Use INSERT INTO clientes (nome, cpf, endereco, telefone) SELECT ... FROM supremacy.', 'GROUP BY cliente_nome garante uma linha por cliente.', 'TRIM() remove espaços do nome.'],
    courseRefs: ['ddl-create-table'],
    evidence: 'Evidência 2: Tabela clientes populada com 9 registros únicos. O endereço agora está em um único lugar.',
    explanation: 'INSERT INTO ... SELECT combina carga com transformação. GROUP BY garante uma linha por cliente.',
  },
  {
    id: 3,
    title: 'Arco 1FN — Identificar Produtos Únicos',
    concept: 'DISTINCT + CAST',
    briefing: `Extraia os produtos únicos. Atenção: o preço está como texto com vírgula ("3.500,00"). Use REPLACE para converter para formato numérico e CAST para transformar em REAL.`,
    objective: 'Liste os produtos únicos com nome, categoria e preço convertido para número REAL.',
    tables: ['supremacy'],
    expectedColumns: ['nome', 'categoria', 'preco'],
    referenceQuery: "SELECT DISTINCT produto_nome AS nome, produto_categoria AS categoria, CAST(REPLACE(REPLACE(TRIM(produto_preco), '.', ''), ',', '.') AS REAL) AS preco FROM supremacy ORDER BY nome;",
    requiredConcepts: ['distinct', 'cast'],
    hints: ['Use REPLACE para remover ponto de milhar e trocar vírgula por ponto decimal.', 'Use CAST(... AS REAL) para converter texto em número.', 'Aplique TRIM antes do REPLACE.'],
    courseRefs: ['dml-functions'],
    evidence: 'Evidência 3: 6 produtos únicos identificados com preços numéricos corretos.',
    explanation: 'REPLACE(REPLACE(texto, ".", ""), ",", ".") converte "3.500,00" → "3500.00". CAST(... AS REAL) transforma em número.',
  },
  {
    id: 4,
    title: 'Arco 1FN — Popular Tabela de Produtos',
    concept: 'INSERT INTO ... SELECT',
    briefing: `Popule a tabela produtos com os dados extraídos na missão anterior. A tabela já existe — basta inserir.`,
    objective: 'Insira na tabela produtos os nomes, categorias e preços (REAL) únicos da planilha.',
    tables: ['supremacy', 'produtos'],
    expectedColumns: ['id', 'nome', 'categoria', 'preco'],
    referenceQuery: "INSERT INTO produtos (nome, categoria, preco) SELECT DISTINCT produto_nome, produto_categoria, CAST(REPLACE(REPLACE(TRIM(produto_preco), '.', ''), ',', '.') AS REAL) FROM supremacy;",
    expectedRows: 6,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'cast'],
    hints: ['Use INSERT INTO produtos (nome, categoria, preco) SELECT DISTINCT ...', 'Converta o preço com CAST e REPLACE como na missão anterior.'],
    courseRefs: ['ddl-create-table'],
    evidence: 'Evidência 4: Tabela produtos populada com 6 registros. Cada produto agora tem sua linha própria.',
    explanation: 'Materializar os dados em uma tabela separada elimina a redundância do preço que se repetia em cada venda.',
  },
  // ═══════════════════════════════════════════
  // ARCO 2: 2FN — Eliminar dependências parciais (missões 5-7)
  // ═══════════════════════════════════════════
  {
    id: 5,
    title: 'Arco 2FN — Identificar Dependência Parcial',
    concept: 'Análise conceitual',
    briefing: `O preço de um produto depende só do produto, não da venda. Se o mesmo produto aparece em 5 vendas, o preço se repete 5 vezes. Isso é dependência parcial. Identifique quais atributos da planilha dependem apenas do produto (e não da combinação venda+produto).`,
    objective: 'Liste os produtos únicos com seus preços — mostrando que o preço depende só do produto.',
    tables: ['supremacy'],
    expectedColumns: ['nome', 'preco'],
    referenceQuery: "SELECT DISTINCT produto_nome AS nome, CAST(REPLACE(REPLACE(TRIM(produto_preco), '.', ''), ',', '.') AS REAL) AS preco FROM supremacy ORDER BY nome;",
    requiredConcepts: ['distinct'],
    hints: ['Selecione nome e preço dos produtos.', 'Use DISTINCT para eliminar duplicatas.'],
    courseRefs: ['normalizacao-2fn'],
    evidence: 'Evidência 5: O preço de cada produto é único — depende só do produto, não da venda.',
    explanation: 'Dependência parcial ocorre quando um atributo não-chave depende de apenas parte da chave composta. O preço depende só do produto_id.',
  },
  {
    id: 6,
    title: 'Arco 2FN — Popular Itens da Venda',
    concept: 'INSERT INTO ... SELECT + JOIN',
    briefing: `A tabela itens_venda deve conter apenas o que depende da combinação venda+produto: quantidade e preço unitário. O resto (nome do produto, categoria) fica em produtos. Popule-a com dados da planilha.`,
    objective: 'Insira na tabela itens_venda os dados que dependem da combinação venda+produto: venda_id, produto_id, quantidade e preco_unitario.',
    tables: ['supremacy', 'produtos', 'itens_venda'],
    expectedColumns: ['venda_id', 'produto_id', 'quantidade', 'preco_unitario'],
    referenceQuery: "INSERT INTO itens_venda (venda_id, produto_id, quantidade, preco_unitario) SELECT s.id, p.id, s.quantidade, CAST(REPLACE(REPLACE(TRIM(s.preco_venda), '.', ''), ',', '.') AS REAL) FROM supremacy s JOIN produtos p ON TRIM(p.nome) = TRIM(s.produto_nome);",
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'join'],
    hints: ['Crie a tabela e use INSERT INTO ... SELECT com JOIN entre supremacy e produtos pelo nome.', 'A quantidade e o preço unitário são os únicos atributos que dependem da combinação venda+produto.'],
    courseRefs: ['joins-inner'],
    evidence: 'Evidência 6: Tabela itens_venda populada com 20 registros. Cada linha representa um produto em uma venda específica.',
    explanation: 'Na 2FN, atributos que dependem de parte da chave composta são movidos para tabelas próprias. quantidade e preco_unitario dependem da combinação venda+produto.',
  },
  {
    id: 7,
    title: 'Arco 2FN — Popular Tabela de Vendas (cabeçalho)',
    concept: 'INSERT INTO ... SELECT',
    briefing: `A tabela vendas (cabeçalho) contém os dados que dependem da venda inteira: data, cliente e vendedor. O valor_total é a soma dos itens. Popule-a com os dados da planilha.`,
    objective: 'Insira na tabela vendas os dados do cabeçalho: id, data_venda e valor_total calculado.',
    tables: ['supremacy', 'vendas'],
    expectedColumns: ['id', 'data_venda', 'valor_total'],
    referenceQuery: "INSERT INTO vendas (id, data_venda, valor_total) SELECT s.id, s.data_venda, SUM(s.quantidade * CAST(REPLACE(REPLACE(TRIM(s.preco_venda), '.', ''), ',', '.') AS REAL)) FROM supremacy s GROUP BY s.id;",
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'sum'],
    hints: ['A tabela vendas guarda os dados do cabeçalho: quando aconteceu, quanto custou.', 'O valor_total = SUM(quantidade × preco_unitario) agrupado por venda.'],
    courseRefs: ['ddl-create-table'],
    evidence: 'Evidência 7: Tabela vendas populada com 20 registros. Cada venda agora tem seus dados de cabeçalho separados dos itens.',
    explanation: 'Separar o cabeçalho (vendas) dos itens (itens_venda) elimina a dependência parcial: os dados do cliente e vendedor não se repetem para cada produto da venda.',
  },
  // ═══════════════════════════════════════════
  // ARCO 3: 3FN — Eliminar dependências transitivas (missões 8-9)
  // ═══════════════════════════════════════════
  {
    id: 8,
    title: 'Arco 3FN — Identificar Dependência Transitiva',
    concept: 'Análise conceitual',
    briefing: `O nome da região e o gerente dependem da região, não diretamente do vendedor. Se a região "Sudeste" mudar de gerente, todos os vendedores daquela região precisariam ser atualizados. Isso é dependência transitiva: vendedor → regiao → gerente.`,
    objective: 'Liste as regiões únicas com seus gerentes — mostrando que esses dados dependem da região, não do vendedor.',
    tables: ['supremacy'],
    expectedColumns: ['regiao', 'gerente'],
    referenceQuery: "SELECT DISTINCT vendedor_regiao AS regiao, regiao_gerente AS gerente FROM supremacy ORDER BY regiao;",
    requiredConcepts: ['distinct'],
    hints: ['Selecione a região e o gerente.', 'Use DISTINCT para eliminar duplicatas.'],
    courseRefs: ['normalizacao-3fn'],
    evidence: 'Evidência 8: 3 regiões únicas com gerentes próprios. Esses dados descrevem a região, não o vendedor.',
    explanation: 'Dependência transitiva: quando A → B → C, e C não depende diretamente de A. Aqui: vendedor → regiao → gerente. O gerente depende da região.',
  },
  {
    id: 9,
    title: 'Arco 3FN — Popular Tabela de Regiões',
    concept: 'INSERT INTO ... SELECT',
    briefing: `Popule a tabela regioes com as regiões únicas extraídas da planilha. Isso elimina a dependência transitiva: o gerente agora depende diretamente do id da região.`,
    objective: 'Insira na tabela regioes os nomes e gerentes das regiões únicas da planilha.',
    tables: ['supremacy', 'regioes'],
    expectedColumns: ['id', 'nome', 'gerente'],
    referenceQuery: "INSERT INTO regioes (nome, gerente) SELECT DISTINCT vendedor_regiao, regiao_gerente FROM supremacy;",
    expectedRows: 3,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'distinct'],
    hints: ['Use INSERT INTO regioes (nome, gerente) SELECT DISTINCT ...', 'As colunas são: nome da região e gerente.'],
    courseRefs: ['ddl-create-table'],
    evidence: 'Evidência 9: Tabela regioes populada com 3 registros. Se o gerente da região mudar, basta 1 UPDATE nesta tabela.',
    explanation: 'Na 3FN, todo atributo não-chave depende diretamente da chave primária. O gerente agora depende do id da região, não transitivamente do vendedor.',
  },
  // ═══════════════════════════════════════════
  // ARCO 4: Relacionamentos — PK, FK e Cardinalidade (missões 10-12)
  // ═══════════════════════════════════════════
  {
    id: 10,
    title: 'Arco Relacionamentos — Popular Vendas com FKs',
    concept: 'Relacionamento 1:N',
    briefing: `Agora conecte as tabelas com FKs. Um cliente pode ter muitas vendas (1:N). A FK fica na tabela do lado "N" (vendas). Atualize a tabela vendas para referenciar clientes e vendedores pelos seus ids.`,
    objective: 'Atualize vendas.cliente_id e vendas.vendedor_id com os ids corretos de clientes e vendedores (subquery correlacionada).',
    tables: ['supremacy', 'clientes', 'vendas'],
    expectedColumns: ['id', 'cliente_id', 'vendedor_id', 'data_venda'],
    referenceQuery: "UPDATE vendas SET cliente_id = (SELECT c.id FROM clientes c WHERE TRIM(c.nome) = TRIM((SELECT s.cliente_nome FROM supremacy s WHERE s.id = vendas.id LIMIT 1))), vendedor_id = (SELECT v2.id FROM vendedores v2 WHERE TRIM(v2.nome) = TRIM((SELECT s.vendedor_nome FROM supremacy s WHERE s.id = vendas.id LIMIT 1)));",
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['update', 'subquery'],
    hints: ['Use UPDATE ... SET ... WHERE para atualizar as FKs.', 'Use subquery para buscar o id do cliente pelo nome.', 'O relacionamento 1:N (um cliente → muitas vendas) é representado pela FK na tabela do lado "N".'],
    courseRefs: ['joins-inner', 'subqueries'],
    evidence: 'Evidência 10: Tabela vendas com FKs populadas. Cada venda agora referencia o cliente pelo id, não pelo nome repetido.',
    explanation: 'O relacionamento 1:N (um cliente → muitas vendas) é representado pela FK na tabela do lado "N". A FK vendas.cliente_id → clientes.id.',
  },
  {
    id: 11,
    title: 'Arco Relacionamentos — Verificar Tabela Intermediária N:N',
    concept: 'Relacionamento N:N',
    briefing: `Um produto pode estar em várias vendas e uma venda pode ter vários produtos. Esse relacionamento N:N exige uma tabela intermediária com PK composta (venda_id + produto_id) e duas FKs. A tabela itens_venda já foi populada na missão 6 — agora confirme que o modelo N:N está correto.`,
    objective: 'Liste as vendas com seus produtos usando JOIN entre vendas, itens_venda e produtos.',
    tables: ['vendas', 'itens_venda', 'produtos'],
    expectedColumns: ['venda_id', 'produto', 'quantidade'],
    referenceQuery: "SELECT iv.venda_id, p.nome AS produto, iv.quantidade FROM itens_venda iv JOIN produtos p ON iv.produto_id = p.id JOIN vendas v ON iv.venda_id = v.id ORDER BY iv.venda_id;",
    requiredConcepts: ['join'],
    hints: ['A tabela intermediária tem PK composta: venda_id + produto_id.', 'Duas FKs: venda_id → vendas.id e produto_id → produtos.id.', 'O relacionamento N:N está resolvido com a tabela itens_venda.'],
    courseRefs: ['joins-inner'],
    evidence: 'Evidência 11: Tabela itens_venda com PK composta e duas FKs. O relacionamento N:N está resolvido.',
    explanation: 'Relacionamentos N:N não podem ser representados com uma FK simples. A tabela intermediária (itens_venda) tem PK composta e uma FK para cada tabela original.',
  },
  {
    id: 12,
    title: 'Arco Relacionamentos — Cliente sem Compras (LEFT JOIN)',
    concept: 'LEFT JOIN + relacionamento opcional',
    briefing: `Nem todo relacionamento é obrigatório. Um cliente pode existir sem ter feito compras. Use LEFT JOIN para encontrar esses casos: o INNER JOIN os esconde, o LEFT JOIN os mostra.`,
    objective: 'Liste todos os clientes (mesmo sem vendas) usando LEFT JOIN com a tabela vendas.',
    tables: ['clientes', 'vendas'],
    expectedColumns: ['nome', 'venda_id'],
    referenceQuery: "SELECT c.nome, v.id AS venda_id FROM clientes c LEFT JOIN vendas v ON c.id = v.cliente_id ORDER BY c.nome;",
    requiredConcepts: ['left join'],
    hints: ['Use LEFT JOIN para incluir clientes sem correspondência.', 'O INNER JOIN esconde clientes sem vendas. O LEFT JOIN os mostra com NULL.'],
    courseRefs: ['joins-inner'],
    evidence: 'Evidência 12: Todos os clientes aparecem — mesmo aqueles que ainda não compraram nada (venda_id = NULL). O relacionamento cliente→venda é opcional do lado do cliente.',
    explanation: 'LEFT JOIN retorna todas as linhas da tabela à esquerda, mesmo sem correspondência na direita. O INNER JOIN só retorna linhas com correspondência em ambas.',
  },
  // ═══════════════════════════════════════════
  // FECHAMENTO (missões 13-14)
  // ═══════════════════════════════════════════
  {
    id: 13,
    title: 'O Teste da Realidade — Atualização em 1 Linha',
    concept: 'UPDATE + benefício da normalização',
    briefing: `O cliente José da Silva mudou de endereço para "Av. Brasil, 500". No modelo normalizado, quantas linhas você precisa atualizar? Apenas 1 — na tabela clientes. Todas as vendas referenciam pela FK.`,
    objective: 'Atualize o endereço do cliente "José da Silva" para "Av. Brasil, 500" na tabela clientes.',
    tables: ['clientes'],
    expectedColumns: ['nome', 'endereco'],
    referenceQuery: "UPDATE clientes SET endereco = 'Av. Brasil, 500' WHERE TRIM(nome) LIKE '%José da Silva%';",
    expectedRows: 1,
    executionMode: 'ddl',
    requiredConcepts: ['update'],
    hints: ['Use UPDATE ... SET ... WHERE para alterar o endereço.', 'Apenas 1 linha precisa ser atualizada — o benefício da normalização!'],
    courseRefs: ['dml-update'],
    evidence: 'Evidência 13: Endereço do José atualizado com 1 único UPDATE. No modelo desnormalizado, seriam 4 updates (uma por venda). A normalização reduz o custo de manutenção.',
    explanation: 'No modelo normalizado, o endereço está em um único lugar (clientes). Todas as vendas referenciam pela FK e "enxergam" a mudança automaticamente.',
  },
  {
    id: 14,
    title: 'Diagrama ER Final — Verificar o Modelo Completo',
    concept: 'Modelagem ER completa',
    briefing: `Última missão: verifique o modelo final. As tabelas são: clientes, produtos, vendedores, regioes, vendas (cabeçalho) e itens_venda (detalhes). As FKs são: vendas→clientes (1:N), vendas→vendedores (1:N), itens_venda→vendas (N:1), itens_venda→produtos (N:1).`,
    objective: 'Liste as tabelas do modelo final com suas respectivas colunas usando PRAGMA table_info.',
    tables: ['clientes', 'produtos', 'vendas', 'itens_venda'],
    expectedColumns: ['tabela', 'coluna'],
    referenceQuery: "SELECT 'clientes' AS tabela, 'id' AS coluna UNION ALL SELECT 'clientes', 'nome' UNION ALL SELECT 'clientes', 'cpf' UNION ALL SELECT 'clientes', 'endereco' UNION ALL SELECT 'clientes', 'telefone' UNION ALL SELECT 'produtos', 'id' UNION ALL SELECT 'produtos', 'nome' UNION ALL SELECT 'produtos', 'categoria' UNION ALL SELECT 'produtos', 'preco' ORDER BY tabela, coluna;",
    requiredConcepts: ['union'],
    hints: ['Liste cada tabela com suas colunas usando UNION ALL.', 'O modelo final tem 6 tabelas interconectadas por FKs.'],
    courseRefs: ['modelagem-er'],
    evidence: 'Evidência 14: Modelo OLTP completo — tabelas normalizadas até a 3FN, com PKs/FKs corretos e cardinalidades definidas. Pronto para o Caso 006!',
    explanation: 'O modelo final: clientes (1)→(N) vendas (1)→(N) itens_venda (N)←(1) produtos, e vendas (1)→(N) vendedores (1)←(N) regioes. Tudo normalizado e relacionadamente correto.',
  },
];

export function getLevel(id) { return LEVELS.find(level => level.id === id); }
export function getTotalLevels() { return LEVELS.length; }
