/**
 * Caso 005 — "A Planilha do Inferno" (Normalização e Relacionamentos)
 * 14 missões em 4 arcos: 1FN (1-4), 2FN (5-7), 3FN (8-9), Relacionamentos (10-12), Fechamento (13-14)
 */

export const CASE_INTRO = {
  title: 'A Planilha do Inferno',
  subtitle: 'Caso #005 — Normalização e Relacionamentos',
  story: `Você foi contratado como estagiário de TI na TechBrasil. Sua primeira missão: transformar a "planilha do sistema" em um verdadeiro banco de dados. O antigo funcionário chamava orgulhosamente o arquivo supremacy.csv de "Banco de Dados Supremo". A diretoria deu um prazo. E o José da Silva já está esperando ser encontrado... de novo. E de novo.`,
  mission: 'Normalize a planilha até a 3FN e modele os relacionamentos corretos.',
};

export const CASE_CONCLUSION = {
  title: 'Modelo Entregue!',
  story: `Parabéns! Você transformou a "Planilha do Inferno" em um modelo OLTP normalizado até a 3FN, com relacionamentos PK/FK corretos. O e-mail de promoção já está na sua caixa: "Analista de Dados Jr" — bem-vindo à TechBrasil! O Caso 006 (sua primeira semana como analista) já está desbloqueado.`,
  cargo: 'Analista de Dados Jr',
  nextSteps: 'O Caso #006 — TechBrasil: Sua Primeira Semana — foi desbloqueado.',
};

export const DATABASE_ANALYSIS = {
  title: 'O Caos da Planilha',
  summary: 'A planilha supremacy mistura dados de clientes, produtos, vendedores e regiões na mesma linha. O mesmo cliente aparece com grafias diferentes, o endereço se repete em cada venda e o gerente é alcançado transitivamente por vendedor → região. Sua missão: separar cada entidade na sua tabela.',
  entities: [
    { name: 'supremacy', role: 'A planilha desnormalizada. Cada linha é uma venda, mas contém dados de 5 entidades diferentes.', key: 'PK id', relations: ['—'] },
    { name: 'clientes', role: 'Tabela alvo: identidade do cliente (nome, CPF, endereço, telefone).', key: 'PK id', relations: ['FK: vendas.cliente_id → clientes.id'] },
    { name: 'produtos', role: 'Tabela alvo: catálogo de produtos (nome, categoria, preço).', key: 'PK id', relations: ['FK: itens_venda.produto_id → produtos.id'] },
    { name: 'vendedores', role: 'Tabela alvo: dados do vendedor. Os atributos da região ficam em tabela própria (3FN).', key: 'PK id', relations: ['FK: vendedores.regiao_id → regioes.id', 'FK: vendas.vendedor_id → vendedores.id'] },
    { name: 'regioes', role: 'Tabela alvo: nome da região e gerente (extraída de vendedores por 3FN).', key: 'PK id', relations: ['FK: vendedores.regiao_id → regioes.id'] },
    { name: 'vendas', role: 'Tabela alvo: cabeçalho da venda (data, cliente, vendedor).', key: 'PK id', relations: ['FK: cliente_id → clientes.id', 'FK: vendedor_id → vendedores.id'] },
    { name: 'itens_venda', role: 'Tabela alvo: detalhes da venda (produto, quantidade, preço). PK composta.', key: 'PK (venda_id, produto_id)', relations: ['FK: venda_id → vendas.id', 'FK: produto_id → produtos.id'] },
  ],
  decisions: [
    { title: 'Separar entidades', explanation: 'Cada assunto (cliente, produto, vendedor, região) deve ter sua própria tabela. Isso elimina redundância e anomalias de atualização.' },
    { title: 'Definir PKs', explanation: 'Toda tabela precisa de uma chave primária que identifique cada linha de forma única.' },
    { title: 'Criar FKs', explanation: 'As chaves estrangeiras "colam" as tabelas separadas de volta, preservando os relacionamentos sem duplicar dados.' },
    { title: 'Resolver N:N', explanation: 'O relacionamento entre vendas e produtos é N:N — exige uma tabela intermediária (itens_venda) com PK composta.' },
  ],
  checkpoints: [
    { question: 'Por que o endereço do cliente se repete em várias linhas?', answer: 'Porque a planilha não separa entidades. No modelo normalizado, o endereço fica só em clientes e todas as vendas referenciam essa entidade pela FK.' },
    { question: 'Por que o gerente não deve ficar repetido na tabela de vendedores?', answer: 'Dependência transitiva: vendedor determina a região e a região determina o gerente. O gerente deve ficar em regioes; se mudar, apenas uma linha será atualizada.' },
    { question: 'Por que precisamos da tabela itens_venda?', answer: 'O relacionamento entre vendas e produtos é N:N. A tabela intermediária resolve com PK composta (venda_id + produto_id) e duas FKs.' },
  ],
};

export const GAMEPLAY = {
  timeline: {
    bonusPoints: 150,
    events: [
      { id: 'anomalia-01', unlockedByMission: 1, sortKey: '2024-01-01T00:00:00', type: 'anomalia', label: 'Cliente repetido 3x com nomes diferentes' },
      { id: 'anomalia-02', unlockedByMission: 5, sortKey: '2024-01-02T00:00:00', type: 'anomalia', label: 'Preço do produto depende só do produto (2FN)' },
      { id: 'anomalia-03', unlockedByMission: 8, sortKey: '2024-01-03T00:00:00', type: 'anomalia', label: 'Gerente depende da região, não do vendedor (3FN)' },
      { id: 'anomalia-04', unlockedByMission: 10, sortKey: '2024-01-04T00:00:00', type: 'anomalia', label: 'N:N entre vendas e produtos exige tabela intermediária' },
      { id: 'anomalia-05', unlockedByMission: 13, sortKey: '2024-01-05T00:00:00', type: 'anomalia', label: 'Endereço normalizado exige apenas uma atualização' },
    ],
  },
  finalChallenge: {
    type: 'confrontation',
    suspectName: 'Diretor da TechBrasil',
    requiredMission: 14,
    steps: [
      { statement: 'Por que o cliente se repete em várias linhas da planilha?', evidenceId: 'anomalia-01', successMessage: 'A planilha não separava entidades. No modelo normalizado, cada cliente tem uma única linha em clientes.' },
      { statement: 'Por que o gerente da região não deve ficar repetido na tabela de vendedores?', evidenceId: 'anomalia-03', successMessage: 'Dependência transitiva (3FN): o gerente descreve a região, não cada vendedor.' },
      { statement: 'O que acontece quando o José muda de endereço?', evidenceId: 'anomalia-05', successMessage: 'No modelo normalizado, 1 UPDATE em clientes resolve. No desnormalizado, seriam 4+ UPDATEs.' },
      { statement: 'Por que precisamos da tabela itens_venda?', evidenceId: 'anomalia-04', successMessage: 'Relacionamento N:N exige tabela intermediária com PK composta e duas FKs.' },
    ],
  },
};

// As missões alteram o mesmo banco e dependem das cargas anteriores.
export const SEQUENTIAL_MISSIONS = true;

export const LEVELS = [
  // ═══════════════════════════════════════════
  // ARCO 1: 1FN — Eliminar grupos repetidos (missões 1-4)
  // ═══════════════════════════════════════════
  {
    id: 1,
    title: 'Arco 1FN — Diagnosticar Variações de Clientes',
    concept: 'DISTINCT + TRIM',
    briefing: `Primeiro passo: diagnosticar as variações de nomes da planilha. O mesmo CPF aparece como "José da Silva", "jose da silva" e "J. da Silva". Use DISTINCT e TRIM para revelar as 11 grafias existentes antes de consolidá-las em 9 clientes.`,
    objective: 'Liste as grafias distintas dos nomes de clientes da planilha supremacy, ordenadas alfabeticamente.',
    tables: ['supremacy'],
    expectedColumns: ['nome'],
    referenceQuery: "SELECT DISTINCT TRIM(cliente_nome) AS nome FROM supremacy ORDER BY nome;",
    requiredConcepts: ['distinct', 'trim'],
    hints: ['Use DISTINCT para eliminar duplicatas.', 'Use TRIM() para remover espaços extras.', "SELECT DISTINCT TRIM(cliente_nome) AS nome FROM supremacy ORDER BY nome;"],
    courseRefs: ['normalizacao-1fn', 'dml-select-where', 'string-functions'],
    evidence: 'Evidência 1: A planilha contém 11 grafias para apenas 9 CPFs — uma anomalia de cadastro que precisa ser consolidada.',
    explanation: 'DISTINCT elimina linhas duplicadas. TRIM() remove espaços extras do início e fim do texto.',
  },
  {
    id: 2,
    title: 'Arco 1FN — Popular Tabela de Clientes',
    concept: 'INSERT INTO ... SELECT',
    briefing: `A tabela clientes já contém um prospect sem compras. Agora insira os 9 clientes únicos da planilha. Use o CPF estável para agrupar e escolha como registro canônico a primeira ocorrência de cada CPF (o menor id).`,
    objective: 'Insira na tabela clientes os nomes, CPFs, endereços e telefones únicos da planilha supremacy.',
    tables: ['supremacy', 'clientes'],
    expectedColumns: ['nome', 'cpf', 'endereco', 'telefone'],
    referenceQuery: "INSERT INTO clientes (nome, cpf, endereco, telefone) SELECT TRIM(cliente_nome), cliente_cpf, cliente_endereco, cliente_telefone FROM supremacy WHERE id IN (SELECT MIN(id) FROM supremacy GROUP BY cliente_cpf);",
    verificationQuery: 'SELECT nome, cpf, endereco, telefone FROM clientes ORDER BY cpf;',
    expectedResultQuery: 'SELECT nome, cpf, endereco, telefone FROM clientes ORDER BY cpf;',
    expectedRows: 10,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'subquery', 'group by'],
    hints: ['Use INSERT INTO clientes (...) SELECT ... FROM supremacy.', 'Em uma subquery, obtenha MIN(id) para cada cliente_cpf com GROUP BY.', 'Filtre a consulta externa pelos ids canônicos e aplique TRIM ao nome.'],
    courseRefs: ['normalizacao-1fn', 'dml-insert', 'cte-subqueries'],
    evidence: 'Evidência 2: Tabela clientes populada com 9 registros únicos. O endereço agora está em um único lugar.',
    explanation: 'INSERT INTO ... SELECT combina carga com transformação. GROUP BY garante uma linha por cliente.',
  },
  {
    id: 3,
    title: 'Arco 1FN — Identificar Produtos Únicos',
    concept: 'DISTINCT + CAST',
    briefing: `Extraia os produtos únicos. Atenção: o preço está como texto com vírgula ("3.500,00"). Use REPLACE para converter para formato numérico e CAST para transformar em REAL.`,
    objective: 'Liste os produtos únicos com nome, categoria e preço convertido para número REAL.',
    tables: ['supremacy'],
    expectedColumns: ['nome', 'categoria', 'preco'],
    referenceQuery: "SELECT DISTINCT produto_nome AS nome, produto_categoria AS categoria, CAST(REPLACE(REPLACE(TRIM(produto_preco), '.', ''), ',', '.') AS REAL) AS preco FROM supremacy ORDER BY nome;",
    requiredConcepts: ['distinct', 'cast'],
    hints: ['Use REPLACE para remover ponto de milhar e trocar vírgula por ponto decimal.', 'Use CAST(... AS REAL) para converter texto em número.', 'Aplique TRIM antes do REPLACE.'],
    courseRefs: ['normalizacao-1fn', 'data-quality', 'string-functions'],
    evidence: 'Evidência 3: 6 produtos únicos identificados com preços numéricos corretos.',
    explanation: 'REPLACE(REPLACE(texto, ".", ""), ",", ".") converte "3.500,00" → "3500.00". CAST(... AS REAL) transforma em número.',
  },
  {
    id: 4,
    title: 'Arco 1FN — Popular Tabela de Produtos',
    concept: 'INSERT INTO ... SELECT',
    briefing: `Popule a tabela produtos com os dados extraídos na missão anterior. A tabela já existe — basta inserir.`,
    objective: 'Insira na tabela produtos os nomes, categorias e preços (REAL) únicos da planilha.',
    tables: ['supremacy', 'produtos'],
    expectedColumns: ['nome', 'categoria', 'preco'],
    referenceQuery: "INSERT INTO produtos (nome, categoria, preco) SELECT DISTINCT produto_nome, produto_categoria, CAST(REPLACE(REPLACE(TRIM(produto_preco), '.', ''), ',', '.') AS REAL) FROM supremacy;",
    verificationQuery: 'SELECT nome, categoria, preco FROM produtos ORDER BY nome;',
    expectedResultQuery: 'SELECT nome, categoria, preco FROM produtos ORDER BY nome;',
    expectedRows: 6,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'cast'],
    hints: ['Use INSERT INTO produtos (nome, categoria, preco) SELECT DISTINCT ...', 'Converta o preço com CAST e REPLACE como na missão anterior.', 'DISTINCT evita cadastrar o mesmo produto mais de uma vez.'],
    courseRefs: ['normalizacao-1fn', 'dml-insert'],
    evidence: 'Evidência 4: Tabela produtos populada com 6 registros. Cada produto agora tem sua linha própria.',
    explanation: 'Materializar os dados em uma tabela separada elimina a redundância do preço que se repetia em cada venda.',
  },
  // ═══════════════════════════════════════════
  // ARCO 2: 2FN — Eliminar dependências parciais (missões 5-7)
  // ═══════════════════════════════════════════
  {
    id: 5,
    title: 'Arco 2FN — Identificar Dependência Parcial',
    concept: 'Análise conceitual',
    briefing: `O preço de um produto depende só do produto, não da venda. Se o mesmo produto aparece em 5 vendas, o preço se repete 5 vezes. Isso é dependência parcial. Identifique quais atributos da planilha dependem apenas do produto (e não da combinação venda+produto).`,
    objective: 'Liste os produtos únicos com seus preços — mostrando que o preço depende só do produto.',
    tables: ['supremacy'],
    expectedColumns: ['nome', 'preco'],
    referenceQuery: "SELECT DISTINCT produto_nome AS nome, CAST(REPLACE(REPLACE(TRIM(produto_preco), '.', ''), ',', '.') AS REAL) AS preco FROM supremacy ORDER BY nome;",
    requiredConcepts: ['distinct'],
    hints: ['Selecione nome e preço dos produtos.', 'Use DISTINCT para eliminar duplicatas.', 'Se o preço depende só do produto, ele pertence à entidade produtos.'],
    courseRefs: ['normalizacao-2fn'],
    evidence: 'Evidência 5: O preço de cada produto é único — depende só do produto, não da venda.',
    explanation: 'Dependência parcial ocorre quando um atributo não-chave depende de apenas parte da chave composta. O preço depende só do produto_id.',
  },
  {
    id: 6,
    title: 'Arco 2FN — Popular Tabela de Vendas (cabeçalho)',
    concept: 'INSERT INTO ... SELECT + GROUP BY',
    briefing: `Crie primeiro o cabeçalho lógico das vendas. Ele contém os dados que dependem da venda inteira: data e valor total. Os itens serão ligados a esses cabeçalhos na próxima missão.`,
    objective: 'Insira na tabela vendas os dados do cabeçalho: id, data_venda e valor_total calculado.',
    tables: ['supremacy', 'vendas'],
    expectedColumns: ['id', 'data_venda', 'valor_total'],
    referenceQuery: "INSERT INTO vendas (id, data_venda, valor_total) SELECT s.id, s.data_venda, SUM(s.quantidade * CAST(REPLACE(REPLACE(TRIM(s.preco_venda), '.', ''), ',', '.') AS REAL)) FROM supremacy s GROUP BY s.id, s.data_venda;",
    verificationQuery: 'SELECT id, data_venda, valor_total FROM vendas ORDER BY id;',
    expectedResultQuery: 'SELECT id, data_venda, valor_total FROM vendas ORDER BY id;',
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'group by', 'sum'],
    hints: ['Use INSERT INTO vendas (...) SELECT ... FROM supremacy.', 'Agrupe por id e data da venda.', 'Calcule valor_total com SUM(quantidade × preço convertido).'],
    courseRefs: ['normalizacao-2fn', 'dml-insert', 'aggregation-groupby'],
    evidence: 'Evidência 6: Tabela vendas populada com 20 cabeçalhos. Agora os itens podem referenciar vendas existentes por FK.',
    explanation: 'O cabeçalho guarda atributos da venda inteira. Criá-lo antes dos itens respeita a integridade referencial de itens_venda.venda_id.',
  },
  {
    id: 7,
    title: 'Arco 2FN — Popular Itens da Venda',
    concept: 'INSERT INTO ... SELECT + JOIN',
    briefing: `A tabela itens_venda contém o que depende da combinação venda+produto: quantidade e preço unitário. Como os cabeçalhos já existem, agora cada item pode respeitar suas duas FKs.`,
    objective: 'Insira na tabela itens_venda: venda_id, produto_id, quantidade e preco_unitario.',
    tables: ['supremacy', 'vendas', 'produtos', 'itens_venda'],
    expectedColumns: ['venda_id', 'produto_id', 'quantidade', 'preco_unitario'],
    referenceQuery: "INSERT INTO itens_venda (venda_id, produto_id, quantidade, preco_unitario) SELECT s.id, p.id, s.quantidade, CAST(REPLACE(REPLACE(TRIM(s.preco_venda), '.', ''), ',', '.') AS REAL) FROM supremacy s JOIN produtos p ON TRIM(p.nome) = TRIM(s.produto_nome);",
    verificationQuery: 'SELECT venda_id, produto_id, quantidade, preco_unitario FROM itens_venda ORDER BY venda_id, produto_id;',
    expectedResultQuery: 'SELECT venda_id, produto_id, quantidade, preco_unitario FROM itens_venda ORDER BY venda_id, produto_id;',
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['insert', 'join'],
    hints: ['Use INSERT INTO ... SELECT com JOIN entre supremacy e produtos.', 'Relacione o produto pelo nome já normalizado.', 'Quantidade e preço unitário pertencem à combinação venda+produto.'],
    courseRefs: ['normalizacao-2fn', 'dml-insert', 'joins-inner-left'],
    evidence: 'Evidência 7: Tabela itens_venda populada com 20 registros e FKs válidas para vendas e produtos.',
    explanation: 'Na 2FN, os atributos da relação ficam na tabela intermediária, enquanto nome e categoria permanecem em produtos.',
  },
  // ═══════════════════════════════════════════
  // ARCO 3: 3FN — Eliminar dependências transitivas (missões 8-9)
  // ═══════════════════════════════════════════
  {
    id: 8,
    title: 'Arco 3FN — Identificar Dependência Transitiva',
    concept: 'Análise conceitual',
    briefing: `O nome da região e o gerente dependem da região, não diretamente do vendedor. Se a região "Sudeste" mudar de gerente, todos os vendedores daquela região precisariam ser atualizados. Isso é dependência transitiva: vendedor → regiao → gerente.`,
    objective: 'Liste as regiões únicas com seus gerentes — mostrando que esses dados dependem da região, não do vendedor.',
    tables: ['supremacy'],
    expectedColumns: ['regiao', 'gerente'],
    referenceQuery: "SELECT DISTINCT vendedor_regiao AS regiao, regiao_gerente AS gerente FROM supremacy ORDER BY regiao;",
    requiredConcepts: ['distinct'],
    hints: ['Selecione a região e o gerente.', 'Use DISTINCT para eliminar duplicatas.', 'O gerente depende da região, não do vendedor individual.'],
    courseRefs: ['normalizacao-3fn'],
    evidence: 'Evidência 8: 3 regiões únicas com gerentes próprios. Esses dados descrevem a região, não o vendedor.',
    explanation: 'Dependência transitiva: quando A → B → C, e C não depende diretamente de A. Aqui: vendedor → regiao → gerente. O gerente depende da região.',
  },
  {
    id: 9,
    title: 'Arco 3FN — Validar Regiões Normalizadas',
    concept: '3FN na prática',
    briefing: `A equipe de cadastro já separou regioes e ligou cada vendedor por regiao_id. Confirme que há uma linha por região e que o gerente está armazenado apenas nessa entidade.`,
    objective: 'Liste o nome de cada região e seu gerente, em ordem alfabética.',
    tables: ['regioes', 'vendedores'],
    expectedColumns: ['regiao', 'gerente'],
    referenceQuery: 'SELECT nome AS regiao, gerente FROM regioes ORDER BY nome;',
    requiredConcepts: ['select'],
    hints: ['Consulte diretamente a tabela regioes.', 'Use alias regiao para a coluna nome.', 'Ordene alfabeticamente pelo nome da região.'],
    courseRefs: ['normalizacao-3fn', 'relational-modeling'],
    evidence: 'Evidência 9: Há 3 regiões normalizadas. Se um gerente mudar, basta 1 UPDATE em regioes.',
    explanation: 'Na 3FN, todo atributo não-chave depende diretamente da chave primária. O gerente agora depende do id da região, não transitivamente do vendedor.',
  },
  // ═══════════════════════════════════════════
  // ARCO 4: Relacionamentos — PK, FK e Cardinalidade (missões 10-12)
  // ═══════════════════════════════════════════
  {
    id: 10,
    title: 'Arco Relacionamentos — Popular Vendas com FKs',
    concept: 'Relacionamento 1:N',
    briefing: `Agora conecte as tabelas com FKs. Um cliente pode ter muitas vendas (1:N). A FK fica na tabela do lado "N" (vendas). Atualize a tabela vendas para referenciar clientes e vendedores pelos seus ids.`,
    objective: 'Atualize vendas.cliente_id e vendas.vendedor_id com os ids corretos de clientes e vendedores (subquery correlacionada).',
    tables: ['supremacy', 'clientes', 'vendedores', 'vendas'],
    expectedColumns: ['id', 'cliente_id', 'vendedor_id', 'data_venda'],
    referenceQuery: "UPDATE vendas SET cliente_id = (SELECT c.id FROM clientes c JOIN supremacy s ON s.cliente_cpf = c.cpf WHERE s.id = vendas.id), vendedor_id = (SELECT v2.id FROM vendedores v2 JOIN supremacy s ON TRIM(s.vendedor_nome) = TRIM(v2.nome) WHERE s.id = vendas.id);",
    verificationQuery: 'SELECT id, cliente_id, vendedor_id, data_venda FROM vendas ORDER BY id;',
    expectedResultQuery: 'SELECT id, cliente_id, vendedor_id, data_venda FROM vendas ORDER BY id;',
    expectedRows: 20,
    executionMode: 'ddl',
    requiredConcepts: ['update', 'subquery'],
    hints: ['Use UPDATE ... SET ... WHERE para atualizar as FKs.', 'Use subqueries para buscar o cliente pelo CPF e o vendedor pelo nome.', 'O relacionamento 1:N (um cliente → muitas vendas) é representado pela FK na tabela do lado "N".'],
    courseRefs: ['relational-modeling', 'joins-inner-left', 'cte-subqueries'],
    evidence: 'Evidência 10: Tabela vendas com FKs populadas. Cada venda agora referencia o cliente pelo id, não pelo nome repetido.',
    explanation: 'O relacionamento 1:N (um cliente → muitas vendas) é representado pela FK na tabela do lado "N". A FK vendas.cliente_id → clientes.id.',
  },
  {
    id: 11,
    title: 'Arco Relacionamentos — Verificar Tabela Intermediária N:N',
    concept: 'Relacionamento N:N',
    briefing: `Um produto pode estar em várias vendas e uma venda pode ter vários produtos. Esse relacionamento N:N exige uma tabela intermediária com PK composta (venda_id + produto_id) e duas FKs. A tabela itens_venda foi populada na missão 7 — agora confirme o modelo.`,
    objective: 'Liste as vendas com seus produtos usando JOIN entre vendas, itens_venda e produtos.',
    tables: ['vendas', 'itens_venda', 'produtos'],
    expectedColumns: ['venda_id', 'produto', 'quantidade'],
    referenceQuery: "SELECT iv.venda_id, p.nome AS produto, iv.quantidade FROM itens_venda iv JOIN produtos p ON iv.produto_id = p.id JOIN vendas v ON iv.venda_id = v.id ORDER BY iv.venda_id;",
    requiredConcepts: ['join'],
    hints: ['A tabela intermediária tem PK composta: venda_id + produto_id.', 'Duas FKs: venda_id → vendas.id e produto_id → produtos.id.', 'O relacionamento N:N está resolvido com a tabela itens_venda.'],
    courseRefs: ['relational-modeling', 'joins-inner-left'],
    evidence: 'Evidência 11: Tabela itens_venda com PK composta e duas FKs. O relacionamento N:N está resolvido.',
    explanation: 'Relacionamentos N:N não podem ser representados com uma FK simples. A tabela intermediária (itens_venda) tem PK composta e uma FK para cada tabela original.',
  },
  {
    id: 12,
    title: 'Arco Relacionamentos — Cliente sem Compras (LEFT JOIN)',
    concept: 'LEFT JOIN + relacionamento opcional',
    briefing: `Nem todo relacionamento é obrigatório. Um cliente pode existir sem ter feito compras. Use LEFT JOIN para encontrar esses casos: o INNER JOIN os esconde, o LEFT JOIN os mostra.`,
    objective: 'Liste todos os clientes (mesmo sem vendas) usando LEFT JOIN com a tabela vendas.',
    tables: ['clientes', 'vendas'],
    expectedColumns: ['nome', 'venda_id'],
    referenceQuery: "SELECT c.nome, v.id AS venda_id FROM clientes c LEFT JOIN vendas v ON c.id = v.cliente_id ORDER BY c.nome;",
    requiredConcepts: ['left join'],
    hints: ['Use LEFT JOIN para incluir clientes sem correspondência.', 'O INNER JOIN esconde clientes sem vendas. O LEFT JOIN os mostra com NULL.', 'O prospect pré-cadastrado aparecerá com venda_id igual a NULL.'],
    courseRefs: ['relational-modeling', 'joins-inner-left'],
    evidence: 'Evidência 12: Todos os clientes aparecem — mesmo aqueles que ainda não compraram nada (venda_id = NULL). O relacionamento cliente→venda é opcional do lado do cliente.',
    explanation: 'LEFT JOIN retorna todas as linhas da tabela à esquerda, mesmo sem correspondência na direita. O INNER JOIN só retorna linhas com correspondência em ambas.',
  },
  // ═══════════════════════════════════════════
  // FECHAMENTO (missões 13-14)
  // ═══════════════════════════════════════════
  {
    id: 13,
    title: 'O Teste da Realidade — Atualização em 1 Linha',
    concept: 'UPDATE + benefício da normalização',
    briefing: `O cliente José da Silva mudou de endereço para "Av. Central, 500". No modelo normalizado, quantas linhas você precisa atualizar? Apenas 1 — na tabela clientes. Todas as vendas referenciam pela FK.`,
    objective: 'Atualize o endereço do cliente "José da Silva" para "Av. Central, 500" na tabela clientes.',
    tables: ['clientes'],
    expectedColumns: ['nome', 'endereco'],
    referenceQuery: "UPDATE clientes SET endereco = 'Av. Central, 500' WHERE cpf = '111.111.111-01';",
    verificationQuery: "SELECT nome, endereco FROM clientes WHERE cpf = '111.111.111-01';",
    expectedResultQuery: "SELECT nome, endereco FROM clientes WHERE cpf = '111.111.111-01';",
    expectedRows: 1,
    executionMode: 'ddl',
    requiredConcepts: ['update'],
    hints: ['Use UPDATE ... SET ... WHERE para alterar o endereço.', 'Filtre pelo CPF, que é estável e único.', 'Apenas 1 linha precisa ser atualizada — o benefício da normalização!'],
    courseRefs: ['normalization-validation', 'dml-select-where'],
    evidence: 'Evidência 13: Endereço do José atualizado com 1 único UPDATE. No modelo desnormalizado, seriam 4 updates (uma por venda). A normalização reduz o custo de manutenção.',
    explanation: 'No modelo normalizado, o endereço está em um único lugar (clientes). Todas as vendas referenciam pela FK e "enxergam" a mudança automaticamente.',
  },
  {
    id: 14,
    title: 'Diagrama ER Final — Verificar o Modelo Completo',
    concept: 'Modelagem ER completa',
    briefing: `Última missão: verifique o modelo final. As tabelas são: clientes, produtos, vendedores, regioes, vendas (cabeçalho) e itens_venda (detalhes). As FKs são: vendas→clientes (1:N), vendas→vendedores (1:N), itens_venda→vendas (N:1), itens_venda→produtos (N:1).`,
    objective: 'Reconstrua cada venda com cliente, vendedor, região, produto, quantidade e preço unitário usando o modelo final.',
    tables: ['clientes', 'vendedores', 'regioes', 'vendas', 'itens_venda', 'produtos'],
    expectedColumns: ['venda_id', 'cliente', 'vendedor', 'regiao', 'produto', 'quantidade', 'preco_unitario'],
    referenceQuery: 'SELECT v.id AS venda_id, c.nome AS cliente, ve.nome AS vendedor, r.nome AS regiao, p.nome AS produto, iv.quantidade, iv.preco_unitario FROM vendas v JOIN clientes c ON c.id = v.cliente_id JOIN vendedores ve ON ve.id = v.vendedor_id JOIN regioes r ON r.id = ve.regiao_id JOIN itens_venda iv ON iv.venda_id = v.id JOIN produtos p ON p.id = iv.produto_id ORDER BY v.id, p.nome;',
    requiredConcepts: ['join'],
    hints: ['Comece em vendas e conecte clientes e vendedores.', 'Ligue vendedores a regioes e vendas a itens_venda.', 'Finalize ligando itens_venda a produtos e use os aliases pedidos.'],
    courseRefs: ['normalization-validation', 'relational-modeling', 'joins-inner-left'],
    evidence: 'Evidência 14: Modelo OLTP completo — tabelas normalizadas até a 3FN, com PKs/FKs corretos e cardinalidades definidas. Pronto para o Caso 006!',
    explanation: 'O modelo final: clientes (1)→(N) vendas, vendedores (1)→(N) vendas, regioes (1)→(N) vendedores e vendas (N)↔(N) produtos por itens_venda.',
  },
];

export function getLevel(id) { return LEVELS.find(level => level.id === id); }
export function getTotalLevels() { return LEVELS.length; }
